### ISSUE TITLE
Variable scoping leaks into child functions

### ISSUE THREAD

**Issue by lmorg** [lmorg/murex#138]
```
» func test2 {
»     set t=123
» }
» func test1 {
»     set t=abc
»     test2
»     $t
» }
» test1
123
```
This should return `abc` since `t` isn't redefined in `test1` however `test2` inherits `test1`'s var table and thus can overwrite `test1`'s value for `t`.

**Comment by lausek** [comment]
Reference file: [variables.go](https://github.com/lmorg/murex/blob/master/lang/variables.go)

`varTables` could be passed to child functions as some sort of copy-on-write structure. I am not aware of such a functionality in Go. How about introducing a new field on `Variables` named e.g.  `shadowTable`?

`shadowTable` is either
- a `varTable` if local modifications were made
- `nil`

If `shadowTable` is set, proxy calls `Set`, `GetValue`, `GetDataType`, `GetString` etc. to it. Otherwise fallback to `varTable`. `Set` is responsible for creating a `shadowTable`.

**Comment by lmorg** [comment]
Hi @lausek, first of all thanks for the feedback.

There is already copy code happening, which is how variables scoped inside a function don't leak out. eg:

```
function test2 {
	for (i=0; i<5; i++) {
		$i
	}
	echo $i
}

function test1 {
	test2
	echo $i
}

test1
```
returns: `01234\n\n`

The issue is I'm cloning `varTable` form the calling function rather than from the root shell process to `varTable` of `test2` thinks it's a child of `test1`.

I've been having a little play with this today myself - inspired by the work you've done - and it seems the fixing this bug is immensely easier than I'd first assumed (which is why I left the bug open for so long). In fact it's just two lines of code: https://github.com/lmorg/murex/pull/209/commits/8119b2dd7a0315aca3d38b374793d41032bdded1#diff-e88ab2716318efef999443b8cd08a012

**Comment by lausek** [comment]
Nice to see that we've made progress on this topic :grin:
