### ISSUE TITLE
builtin ‘qr’: other output formats could be useful

### ISSUE THREAD

**Issue by kseistrup** [lmorg/murex#196]
Other formats than PNG could be useful. The `qrencode` command offers several:

```sh
$ qrencode -h | awk '$1 == "-t"'
  -t {PNG,PNG32,EPS,SVG,XPM,ANSI,ANSI256,ASCII,ASCIIi,UTF8,ANSIUTF8}
```

E.g.:

![qr](https://user-images.githubusercontent.com/25586/72436148-0e27b600-37a0-11ea-8d92-eeee9756b67e.png)

**Comment by lmorg** [comment]
This isn't yet part of the core shell (though it probably should be) but there is a module that will do this. You can install it with the following command:
```
murex-package: install https://github.com/lmorg/murex-module-open-image.git
```

This then allows you to use `open` to print images directly to the terminal:
```
echo "hello world" -> qr -> open
```

A variety of output formats are supported to:
```
» config -> [[ /open/image/Options ]]
[
    "auto",
    "compatible",
    "kitty",
    "iterm",
    "terminology",
    "sixel"
]
```

In theory the module should auto pick the best supported format for your terminal emulator, however it doesn't quite work on iTerm just yet. So if you're using macOS + iTerm2 then you might additionally need to add the following to your `~/.murex.profile` until I've worked out the niggles with iTerm2's ANSI escape sequences:
```
config set open image compatible
```

---

With regards to supporting other image formats, it's possible I could write marshallers for specific image formats so you could then do something like:
```
echo "hello world" -> qr -> format jpeg -> > file.jpeg
```

It's not as convenient as using `qrencode` but I'm a little concerned about how bloated _murex_ is already getting. In fact I'm not entirely sure `qr` even belongs in _murex_ to begin with.

**Comment by kseistrup** [comment]
> That all said, I'm not entirely sure `qr` even belongs in `murex` to begin with.

Neither am I (but I am not the author). There are a number of commands (`base64`, `bz2`, `gz`, `qr`) that I don't feel belong in `murex`: they already have splendid implementations on disk, and I am unsure what is gained by making these builtins, unless `murex` is running on a minimal OS and `murex`aspires to be some kind of `busybox`.

**Comment by lmorg** [comment]
busybox was an inspiration funny enough. The other reasoning was because I wanted the shell to be usable on Windows too - which doesn't have good support for `base64` et al. Then if it's enabled on Windows it would have to be enabled on all platforms for shell scripting compatibility. 

The amount of code those builtins add actually isn't much however I do think you're absolutely right that they really have no place being included.

At the moment they're all optional builtins anyway (albeit included by default). What I think I'll do is make then excluded by default (except on Windows - at least for now). That way the option is still available but I'm not contaminating the code base. I should also do the same with `sleep` too. I have no idea why I thought _murex_ needed `sleep` as a builtin....

**Comment by kseistrup** [comment]
Ah, Windows – then it all makes sense. And it also makes sense to exclude those builtins by default, except on Windows. I have a much clearer picture now, thanks.

I'm fine with having this issue closed, unless you feel the need to keep it open.

**Comment by lmorg** [comment]
Awesome. I've made a commit but I'm going to leave it in the `develop` branch for a few days to shake out any breaking changes (if any should exist)

In the mean time I'll close this issue.

Thank you
