### ISSUE TITLE
Jerking cursor while typing

### ISSUE THREAD

**Issue by nu8** [lmorg/murex#252]
When I am typing a command into the shell, with every key press, the cursor
jumps from the start of the line, to the current cursor position.

It is quite distracting. I have a video to demonstrate:

https://github.com/lmorg/murex/files/5252790/2020-09-20.17-00-25.zip

**Comment by lmorg** [comment]
@nu8 Hi, sorry I've just spotted this issue; work and home life has been pretty intense during pandemic :(

Anyhow, the cursor issue. This is a result of a slight latency between typing and the line getting redrawn for colourisation. It's not something that is visible in all terminal emulators but I can definitely see the annoyance in yours.

Unfortunately it's not an easy problem to solve because I either disable the initial draw and only do one pass with colourised text, but that would add latency when pressing keys to them appearing on screen, or keep as is and see a cursor hopping around. I figure the former would actually case more of annoyance for usability than the latter. That said, there's definitely some refinements that can (and does) need to happen with my readline implementation -- and in fact I do plan on rewriting large portions of it....at some point. Not that good intentions helps you right here and now.

Disabling colourised text and the spell checker might help because that would mitigate the need for a send pass over the line:

```
config set shell spellcheck-enabled false
conflg set shell syntax-highlighting false
```

Also are you able to share some details about your test machine please so I can build up a picture for how the shell performs on different systems:

- OS (eg Linux, macOS, Windows?)
- Terminal emulator (eg Konsole, iTerm, minTTY?)
- Host specifications (CPU, RAM)
- Any other specifics (eg running in WSL? Running inside a VM?)

Thank you

**Comment by nu8** [comment]
closing this because more serious issue found
