### ISSUE TITLE
Bracket close auto-completion always placed at end despite currently existing braces

### ISSUE THREAD

**Issue by iandwelker** [lmorg/murex#275]
If you type `{ ` into murex's prompt, it will autocomplete with a closing curly brace to create `{ }`, but if you add a hard bracket just before the closing curly brace, then hit space (so that it looks like `{ [ }`), murex will autocomplete the inner hard bracket at the end of the line, so that the whole line looks like `{ [ } ]`. This pattern continues as you add more brackets. I suspect it should autocomplete to `{ [ ] }` instead of what it currently does.

This also happens if you switch the hard brackets and curly braces (so that it creates `[ { ] }` instead).

(Fantastic project, by the way -- I've been using zsh for a while but the ease-of-use features that murex has, along with being much faster, completely blows zsh out of the water in my opinion. Thank you so much for creating this.)

Edit: Happening on MacOS Big Sur 11.2, murex version 1.5.4100 beta. I looked through the source code a bit and suspect the issue lies around lines 58 & 83 of `shell/syntax.go`. I would love file a PR, but unfortunately I don't know go.

**Comment by lmorg** [comment]
Hi @iandwelker yeah the bracket completion is really shoddy code on my part. Really I need a proper syntax parser to pair up the brackets and judge where to place the closing characters and which character to close. But in reality I just count the number of opening vs closing characters. So the whole code here needs a re-write.

There is a little bit of logic that checks if there is too many closing brackets and if so it will remove the closing bracket (i think if the last character is a closing bracket) so some of the annoyance you've described is handled automatically if you keep inputting code. But it is a far cry from being as intuitive as one expects with a (for example) IDE.

Also thanks for your kind words :)

**Note to self:**
While I'm doing a rewrite I should also add support for disabling automatic syntax completion too. eg
`config set shell syntax-completion` so users who do not like this behaviour can turn it off.

**Comment by lmorg** [comment]
@iandwelker There is now a branch with an updated syntax completion: https://github.com/lmorg/murex/tree/syntax-completion-parser

There's still some work I need to do to fix all of the annoying edge cases but the parser that's used for the syntax completion has been beefed up somewhat and the shell should be usable. So you're welcome to pull from that branch if you find this bug particularly painful. Otherwise I'd expect it to be merged back into the master branch (and relevant binaries auto-built) some time next month (gives myself a few weeks of usage to catch anything annoying that I might have forgotten to write unit tests around).

**Comment by lmorg** [comment]
I've merged some these changes into `develop` and `master`. While there's still some improvements that can be made (and happy to take on any feedback in that area), I don't see the need for this to occupy a dedicated feature branch any longer. So that branch has been removed and you're safe to use either `develop` or `master` as you were.

If you were pulling from the pre-compiled binaries then those will be generated Monday morning as part of the automated build process.

**Comment by iandwelker** [comment]
Sorry for my lack of response &mdash; the updates have been working well for me. I really appreciate the time that you took to fix this :)

**Comment by lmorg** [comment]
@iandwelker 

Just an FYI that I've completely rewritten the syntax completion and that will be pushed out in v2: https://github.com/lmorg/murex/pull/312

The syntax completion is hugely upgraded. Feel free to raise an issue if you do run into any new problems and/or regressions :)

**Comment by iandwelker** [comment]
Thanks for letting me know! 
I have noticed two small issues with the v2 update, but they aren't the same things as I opened this issue for initially. Would you prefer I describe them here or open separate issues and link them here?

**Comment by lmorg** [comment]
Happy for you to share here

**Comment by iandwelker** [comment]
So sorry, I just realized that I never responded to this &mdash; that's my bad. However, I just pulled and built the latest version, and both of the issues that I was running into before have been resolved. I'll close this issue, since I'm not seeing any more bugs with autocompletion.
