### ISSUE TITLE
Index not working as expected

### ISSUE THREAD

**Issue by noonien** [lmorg/murex#282]
```
» python -c 'for i in range(0,5): print(i)'
0
1
2
3
4
» python -c 'for i in range(0,5): print(i)' -> [0]
0
» python -c 'for i in range(0,5): print(i)' -> [1]
» python -c 'for i in range(0,5): print(i)' -> len
5
» python -c 'for i in range(0,5): print(i)' -> format json 
[
    [
        "0"
    ],
    [
        "1"
    ],
    [
        "2"
    ],
    [
        "3"
    ],
    [
        "4"
    ]
]
```

`cat /cpu/procinfo -> [0]` also has a weird output

This happens on murex installed with `go get -u github.com/lmorg/murex` from the latest commit at this point in time: https://github.com/lmorg/murex/commit/b794602672120e49766c3ff22c304fc56e5f013e

**Comment by lmorg** [comment]
Hi @noonien 

That's because by default any output from a non-murex process is cast as a "generic" type (piss poor name - it's an evolutionary thing and I should probably look to change it) and the way generic data is treated is as columns then rows. Much like with bash. The caveat here is that index also supported named columns.

So the python output is producing one column of data with the title row being `0`.

Another example of this in action would be the following:
```
~ » ps aux -> head -n5
USER               PID  %CPU %MEM      VSZ    RSS   TT  STAT STARTED      TIME COMMAND
_windowserver      138  29.3  0.7  8548808 115532   ??  Ss   18Feb21 1476:50.11 /System/Library/PrivateFrameworks/SkyLight.framework/Resources/WindowServer -daemon
laurencemorgan    1348  24.1  3.3  9867248 556148   ??  S    18Feb21 1066:44.16 /Applications/Firefox.app/Contents/MacOS/firefox -foreground
laurencemorgan    5242  17.2  0.4  5017100  68376 s001  R+    8:35pm   0:39.90 murex
laurencemorgan     353   8.9  2.1  5764200 346052   ??  S    18Feb21  30:54.90 /Applications/iTerm.app/Contents/MacOS/iTerm2

~ » ps aux -> [USER PID %MEM] -> head -n5
USER    PID     %MEM
_windowserver   138     0.7
laurencemorgan  1348    3.3
laurencemorgan  5242    0.4
laurencemorgan  353     2.1
```

What format does is change a data from one format to another. eg
```
~ » ja [1..5]
[
    "1",
    "2",
    "3",
    "4",
    "5"
] 

~ » ja [1..5] -> format yaml
- "1"
- "2"
- "3"
- "4"
- "5"
```

So in your example, `format` is working correctly too because one column table stored in a 2 dimensional array would look kind of weird like that.

What you needed to do was either specify the column number (this part isn't well documented, apologies for that) by using the colon character. Think of a table of data like a spreadsheet with the address at the start being the column number and the address at the end being the row number, and place the column on either side of the data depending on which field you wish to denote:
- :column
- row:
- title (no colon)

Thus...
```
~ » python -c 'for i in range(0,5): print(i)' -> [:0]
0
1
2
3
4

~ » python -c 'for i in range(0,5): print(i)' -> [4:]
4
```

The other approach could have been to recast Pythons output into a different type (not reformat, we want to keep the data the same but change how it's parsed).

The `str` data type is for raw lists (ie not loosely tabulated data `ps` or `ls -l` etc). Looking at the docs, I haven't written anything for `str` yet either...so I owe you another apology here....

```
~ » python -c 'for i in range(0,5): print(i)' -> cast str -> [3]
3
```

I will grant you none of this is obvious though. :-/

**Comment by lmorg** [comment]
Hi @noonien 

Coming back to this with a sober head, your following example does still break the assumptions made above:
```
» python -c 'for i in range(0,5): print(i)' -> [0]
0
```

So you're right something is amiss. Thanks for raising this.

**Comment by lmorg** [comment]
Found the bug and turns out it was a stupid off-by-one error.

I've fixed that and added some much needed testing to confirm the fix

```
» python -c 'for i in range(0,5): print(i)' -> [0]
0
1
2
3
4
```

The question still remains whether this is intuitive behaviour....
