### ISSUE TITLE
Any way to pass in array as set of arguments?

### ISSUE THREAD

**Issue by iandwelker** [lmorg/murex#289]
In bash, you can pass in arguments (`$@`) from one function to another function or command. In murex, however, I can't find a good way to do this. Here's an example of what I mean:

```sh
# in bash
get_args() {
    echo ${#@}
    echo "$@"
}

args() {
    get_args "$@"
}

args this is a test
# outputs:
# 4
# this is a test

# however, in murex...
function get_args {
    out ${$ARGS -> len}
    out $ARGS
}

function args {
    get_args $ARGS
}

args this is a test
# outputs:
# 2
# ["get_args","[\n    \"args\",\n    \"this\",\n    \"is\",\n    \"a\",\n    \"test\"\n]"]
```

Is there any way to emulate bash's behavior here? I've tried things like:
```sh
function args {
    get_args ${$ARGS -> foreach i { ( $i) }}
}
```
But, as far as I can tell, it always results in *basically* the same behavior &mdash; the array always being interpreted as a single command line argument as opposed to multiple space-delimited arguments. How would I make murex interpret it as multiple space-delimited arguments?

**Comment by lmorg** [comment]
Arrays are prefixed with `@`.

So to use your examples:
```
~ » function get_args { out $ARGS }
~ » get_args 1 2 3
[
    "get_args",
    "1",
    "2",
    "3"
]

~ » function get_args { out @ARGS }
~ » get_args 1 2 3
get_args 1 2 3
```

Likewise for subshells. If you want the subshell to return the results as a string you use `${}` but if you want it to return as an array you use `@{}`.

The idea behind this is so that spaces don't accidentally get turned into separate parameters -- the most typical problem space being file names. With murex you don't need to remember to do syntax like: `rm "$VAR"` where $VAR could contain a space. You explicitly state how the variable is expanded.

This is loosely based on Perl with the `$SCALAR` vs `@ARRAY` tokens.

**Comment by iandwelker** [comment]
That's actually super useful; I always that *sh quirk was really bizarre, so I'm glad it's solved here. Thanks for the quick response!
