### ISSUE TITLE
Fail fast

### ISSUE THREAD

**Issue by piegamesde** [lmorg/murex#296]
When a subcommand dies with non-zero exit code, I'd expect the shell to handle this and bail out unless the failing code has been wrapped in a try-catch-block.

I came here in the hope of finding a replacement for my Bash scripts, and the first thing I write in every Bash script is precisely `set -eo pipefail`.

**Comment by lmorg** [comment]
First of all it is important to note that a non-zero exit status doesn't specifically denote an error. That's the general convention but there is no standard that specifically states non-zero is an error. I've experienced some tools that return non-zero codes for informational purposes. It's also important to remember that not all programs return a non-zero error on exit.

The reason I caveat that is because there are a few issues with `set -eo pipefail`:
- It assumes non-zero exit statuses are a failure
- It assumes failures will return a non-zero exit status

_murex_ attempts to solve this problem with `try` (roughly equivalent to `set -e`) and `trypipe` (roughly equivalent to  `set -o pipefail`. Where _murex_ differs from Bash is that _murex_ checks the STDERR and STDOUT streams inside a `try` and `trypipe` block and if STDERR is greater than STDOUT (per bytes written) then it assumes there is an error even if the exit status is 0. So it catches any programs that don't return non-zero exit statuses.

The benefit of having that as a block rather than default behaviour is threefold:
1. not all non-zero exit statuses are a failure. Such programs would never work in a shell that strictly treated this convention as a fact. So for compatability reasons we can't assume all non-zero exit statuses are a failure

2. not all failures are terminal. For example `mkdir /foo/bar` might fail if **/foo/bar** already exists. There are some workarounds like `mkdir -p /foo/bar` but the `-p` flag isn't portable (in an ideal world you might want to check if the directory already exists before running `mkdir` but this contrived example is just to demonstrate that you might not want to fail on an error).

3. exiting the script on an error is a pretty crappy way of error handling. Having a `try` / `trypipe` block enables you to catch any errors and do something more meaningful -- even if that is just printing a message saying "Script failed". At least the user executing the script has clear feedback as to what happened. Equally you might want several different blocks of code to have slightly different error handling. Another contrived example:
    ```
    trypipe {
        # mkdir / cd / etc
    }
    catch {
        err "Failed to create install location"
        exit 1
    }
    
    trypipe {
        # make install
    }
        catch {
        err "Failed to install application"
        exit 1
    }
    
    out "Install complete"
    ```

The reason `try` and `trypipe` are different commands is because in order for `trypipe` to work (ie prevent subsequent commands from executing if a proceeding one fails) you have to break the highly concurrent nature of pipelines (ie in any given POSIX pipeline all commands are running concurrently). For most usages this isn't a problem, but if you're running pipelines against _massive_ datasets then running the pipeline sequentially will introduce huge performance penalties. So by having distinct `try` and `trypipe` schedulers it allows the developer to opt for the run mode that gives them the best error handling vs performance throughput for their particular use case.

**Comment by lmorg** [comment]
@piegamesde 

More documentation on error handling and schedulers:
- `try`: https://murex.rocks/docs/commands/try.html
- `trypipe`: https://murex.rocks/docs/commands/trypipe.html
- `catch`: https://murex.rocks/docs/commands/catch.html
- How pipeline commands are scheduled: https://murex.rocks/docs/user-guide/schedulers.html

Also `if` can be pretty nifty error handling too:
- example: `!if { which foobar } then { err "foobar is not installed" }`
- `if` doc: https://murex.rocks/docs/commands/if.html
- Discussion: https://news.ycombinator.com/item?id=26285248

Lastly if robust shell scripts are your aim then you'd better include some tests in there. _murex_ has a testing framework built into it that supports a few different testing methodologies:
- **inlined test**: this is where you write tests inside your function and attach them to a process via a special "test" pipe. When that function is executed the tests are either ignored (normally), or logged (when test mode is enabled). If the test mode is enabled then the tests attached to the process check that the process is in the expected state (eg the right type of content written to STDOUT et al, exit code, etc). This is a good way of monitoring processes in scripts and helps massively with debugging.
- **state**: this really should have been called "watch" since that's the crux of what it is, albeit it's not a simple variable watch like you'd normally see in an IDE. With "state tests" you can write shell scripts as part of the state checks so you can have greater flexibility into the runtime inspection. This is also attached to processes via a special pipe.
- **unit tests**: this is much closer to the kind of testing one typically thinks about as developer. Unit tests, when run, will also output the inlined and state results too and the reporting format can be changed too.
- **debug**: There is also a debug mode which is more verbose. It prints, unsurprisingly, debug messages I've written into the shell. But it also prints error messages that might normally be suppressed (eg in the `if` example above, you wouldn't normally want `which` to print it's error message since you only care about whether it passed or failed. But with debug turned on those error messages would also be printed).

Documentation:
- `test`: https://murex.rocks/docs/commands/test.html
- `debug`: https://murex.rocks/docs/commands/debug.html

Documentation is an on-going project in it's own right. So some of those docs might lack a little of the detail I've posted here. Please bare with me on this, I'm working on it :)

**Comment by piegamesde** [comment]
> not all non-zero exit statuses are a failure. […] not all failures are terminal

Having zero exit codes on success indeed is a *convention*, and almost all programs except some very old tools adhere to it. `set -e` is strongly recommended as Bash best practice for a reason. In case a program does not adhere to it, there are still possibilities to handle it: in Bash, one can add `|| true` to "swallow" the exit code, and some CLI applications have special flags to improve error handling. In Murex, there's try-catch to add explicit error handling. An empty catch block would be the equivalent of `|| true`.

> exiting the script on an error is a pretty crappy way of error handling.

Yes it is. But it is still better than silently continuing on an error.

**Comment by lmorg** [comment]
I can add a flag that enables that default so your scripts could say `#!/usr/bin/murex --try` for example. That would be an easy addition. Likewise for `--trypipe`. But having `trypipe` enabled by default breaks concurrency (which would be a massive loss) and `try` only fixes _some_ of the problems (ie commands at the end of pipes) which isn't a predictable default from a usability perspective. So I don't see either of them as zero-loss changes if they were to become the new defaults. Whereas the current default is at least the most predictable default due to it's explicitness even if it isn't the most ideal from a error capturing perspective. Given unpredictability in shells is a major cause of bugs, this is one of the most important areas I was seeking to fix with _murex_.

So the flag option would at least solve the problem of having to write additional lines of code while still making error handling explicit and allow the developer to be in control of the scheduler too (ie when processes run concurrently or sequentially).

**Comment by lmorg** [comment]
@piegamesde 

The scheduler_flags branch now contains a version of _murex_ with the `--try` and `--trypipe` flags which will enable the default behaviour you desire.

These flags currently only work for code that is loaded via `./murex example.mx` or `#!/usr/bin/murex --trypipe`, and for code passed as a command line parameter via `./murex -c 'out "example"'`. However this is just the first commit so future pushes will also include support for the REPL shell too. There's also no tests included in this push, that will also follow shortly. So keep an eye on that branch for updates.

**Comment by piegamesde** [comment]
Thank you.

**Comment by lmorg** [comment]
Tests added, code pushed to `master` branch. New executables will be compiled in tonight / Monday mornings weekly build run.

**Comment by piegamesde** [comment]
Works fine for me.
