### ISSUE TITLE
Differences to Elvish

### ISSUE THREAD

**Issue by bentxt** [lmorg/murex#298]
Hi,
AFAIK the elvish shell is a little older then murex, but the two are similar, at least from the outside. 

Personally, there are things I like in murex for example the builtin vim mode, or that it has a switch expression. But I like elvish for being closer to traditional (bash) shell syntax and really stick with the pipe syntax.

Either way, what I think is really great, that both shells could potentially replace my useful but flawed Perl/Bash combo. The only thing I have to do is to decide which shell I should choose: Murex vs Elvish.

Could you help me with the decision by providing a few insight in your decision to create the murex shell, when there already was the elvish shell? What do you miss, what did you choose to do differently?

Thanks a lot
Ben

**Comment by lmorg** [comment]
Hi @bentxt 

_murex_ does support the regular pipe token, `|`, as well. But you're right that _murex_'s syntax does otherwise differ significantly from Bash. I'd started _murex_ a little while before the first commit on Github as a tool to help with some problems I was having when iterating over complex datasets in Bash (like Apache log files or JSON objects). It grew organically from there into what it is today. This is why typed pipes and `foreach` loops using C-style braces are at the core of the language.

As for why you'd chose _murex_ over _elvish_, well that's entirely personal preference. It's amusing how similar the two are but those similarities are entirely coincidental. I've never used _elvish_ personally because by the time I'd discovered _elvish_ existed I was already using _murex_ as my full time shell. For me, the appeal of _murex_ is the fact that I've written it so it's tailored to my preferences and if I come across something I want or something I don't like, I can change it myself. Clearly this isn't going to be what sells _murex_ to anyone else, but I've got to be honest about my own motives :)

As for what _murex_ offers that _elvish_ doesn't. I'm not super confident on what features _elvish_ has so I'll instead post a list of lesser common shell features that _murex_ supports, some of which _elvish_ will likely have too:
- spell checking support (not enabled by default and requires `aspell` installed)
- parsing of man pages to provide auto-completion hints
- a dedicated hint text line, which provides context sensitive insights, so you know exactly what every alias, symlink, etc points to.
- all STDERR output is colourised in red
- slower auto-completions don't lock the shell, they get deferred to the background and update the completion items when completed. So the shell should remain snappy while supporting more advanced options (eg recursive directory searches)
- Not just support for JSON, but YAML, S-Expressions, CSV, and others. Also can parse tabulated data like `ps -fe`, `ls -l` as structured data too https://murex.rocks/docs/GUIDE.type-system.html
- There's some higher level language abstracts too like unit testing https://murex.rocks/docs/commands/test.html (document needs enhancing)
- support for macros when sending ^z 
- auto-completion syntax is as simple or as complicated as you want to make it. There's a simple JSON template you can use if you just want to add a few flags, or you can write your own dynamic completions like with every other shell https://murex.rocks/#powerful-autocompletion
- every function, variable and alias is stored with data about which file loaded said property and at what time. So tracing functionality is extremely easy https://murex.rocks/docs/user-guide/fileref.html
- _murex_ has it's own module system which makes it easy to share profiles, common functions and ensure your own _murex_ environment is easy to keep consistent across multiple systems https://murex.rocks/docs/user-guide/modules.html
- strings and arrays are treated distinctly so you can't accidentally pass a string as multiple parameters (eg a file name with a space character in its name) https://github.com/lmorg/murex/issues/289
