### ISSUE TITLE
Is this usable from within Go?

### ISSUE THREAD

**Issue by NightMachinary** [lmorg/murex#331]
I really like to have a good API to work with processes, globbing, and files in Go. I wonder if this project can be used that way?

**Comment by lmorg** [comment]
It could, but without knowing more about your project I suspect _murex_ would be overkill for your needs since Go provides a lot of the basics out of the box:

- Processes: https://golang.org/pkg/os/exec/
- Glob: https://golang.org/pkg/path/filepath/#Glob
- Files: https://golang.org/pkg/path/filepath/#Walk / https://golang.org/pkg/io/ioutil/#ReadDir

The processes part is the most tricky to get right. And if you're wanting to manage processes which you're not spawning from Go, then things will get even trickier still (you might then need the `os` package, eg https://golang.org/pkg/os/#Process).

**Comment by NightMachinary** [comment]
@lmorg Ideally, I like to be able to just use murex code, while having the ability to interpolate variables from Go, and also use the output as Go objects. An example of such an API is https://github.com/NightMachinary/brish , which does this for zsh and Python.

**Comment by NightMachinary** [comment]
Another example is https://github.com/rust-shell-script/rust_cmd_lib , which implements a custom shell language in Rust.

**Comment by NightMachinary** [comment]
@lmorg Thanks! 

Is there some API to quote a string for `murex`? E.g., in `zsh`, I use:
```
gquote () {
	print -r -- "${(q+@)@}"
}
```

```
❯ gquote $'\0'"hi \"Alice\"\! '_'"           
                                                              
$'\C-@hi "Alice"! \'_\''
```

With a quoting function, it would be much easier to insert variables into the command:
```
func example() {
    someFile := "/path/to/file"
	p, err:=Shell(`ls ` + mq(someFile))
	if err!=nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Println(p.Stdout)
}
```

Ideally, `mq` would support varargs, and quote them appropriately as shell arrays:
```
func example() {
    someFile := "/path/to/file"
    someOtherFile := "/path/to/file2"
	p, err:=Shell(`ls ` + mq(someFile, someOtherFile))
	if err!=nil {
		fmt.Println(err.Error())
		return
	}

	fmt.Println(p.Stdout)
}
```

`mq` probably needs generics though? I don't know much Go, so I'm not sure. It just needs to call the `String()` method on its arguments first, and then murex-quote them all aand return a single string.

**Comment by lmorg** [comment]
There isn't an API to do this because _murex_ parametrises variables. eg the following code in bash/zsh vs _murex_:
```
export foobar="hello world"
ls $foobar
```
In bash/zsh you'd get the following
```
ls: cannot access 'hello': No such file or directory
ls: cannot access 'world': No such file or directory
```
because "hello world" is expanded in the shell as `ls hello world`. But in _murex_ you get
```
ls: cannot access 'hello world': No such file or directory
```
because _murex_ passes $foobar as a token in the command line and expands it as one parameter when the application `ls` launches.

A similar comparison in webdev would be the different between writing SQL via infixing variables (unsafe) vs parametrised queries (safe).

This means that in _murex_ you also don't need to remember all those annoying edge cases like remembering to put double quotes around variables that can cause your shell scripts to blow up in unexpected ways.

Thus if you were to infix a variable into your Go cmd string you'd break the safety that _murex_ was built around.

---

For your use case, _murex_ might be a little overkill. You could probably achieve similar results by writing your own package. eg

```go
func Bash(cmd string) {
    bash := exec.Command("bash", "-c", cmd)
        if err := bash.Run(); err != nil {
            log.Fatal(err)
        }
}
```

from there you can do all the infixing you like. eg:
```go
cmd := fmt.Sprintf(`ls "%s"`, filename)
bash(cmd)
```
