### ISSUE TITLE
Install on Fedora 34 fails (issue with `go get` + `bzr`)

### ISSUE THREAD

**Issue by sebastien** [lmorg/murex#342]
Hi there, just a heads up that running the install on Fedora 34 does the following:

```bash
$ go get -u github.com/lmorg/murex
go: downloading github.com/lmorg/murex v0.0.0-20210513200202-3333d40db654
go get: github.com/lmorg/murex@none updating to
github.com/lmorg/murex@v0.0.0-20210513200202-3333d40db654 requires
labix.org/v2/mgo@v0.0.0-20140701140051-000000000287: unrecognized import path "labix.org/v2/mgo": GOVCS disallows using bzr for public labix.org/v2/mgo; see 'go help vcs'
```

Running `export GOVCS='*:git|hg|bzr'` gets me further:

```bash
go: downloading golang.org/x/sys v0.0.0-20210423185535-09eb48e85fd7
go: downloading github.com/eliukblau/pixterm v1.3.1
go: downloading golang.org/x/crypto v0.0.0-20210421170649-83a5a9bb288b
go: downloading github.com/fsnotify/fsnotify v1.4.9
go: downloading github.com/Knetic/govaluate v3.0.0+incompatible
go: downloading golang.org/x/crypto v0.0.0-20210513164829-c07d793c2f9a
go: downloading golang.org/x/sys v0.0.0-20210514084401-e8d321eab015
go: downloading github.com/phayes/permbits v0.0.0-20190612203442-39d7c581d2ee
go: downloading github.com/disintegration/imaging v1.6.2
go: downloading github.com/lucasb-eyer/go-colorful v1.0.3
go: downloading golang.org/x/image v0.0.0-20191206065243-da761ea9ff43
go: downloading github.com/lucasb-eyer/go-colorful v1.2.0
go: downloading golang.org/x/term v0.0.0-20201126162022-7de9c90e9dd1
go: downloading golang.org/x/image v0.0.0-20210504121937-7319ad40d33e
go: downloading golang.org/x/term v0.0.0-20210503060354-a79de5458b56
github.com/lmorg/murex imports
	github.com/lmorg/murex/builtins imports
	github.com/lmorg/murex/builtins/imports_build: cannot find module providing package github.com/lmorg/murex/builtins/imports_build
go: downloading github.com/Knetic/govaluate v1.5.0
```

but still does not complete

```bash
$cd $GOPATH/src/github.com/lmorg/murex
bash: cd: /home/spierre/.local/share/go/src/github.com/lmorg/murex: No such file or directory
```

As a result, I can't install Murex on Fedora 34.

**Comment by lmorg** [comment]
Hi @sebastien 

Thanks for the bug report. Could you try navigating to `/home/spierre/.local/share/go/src/github.com/lmorg/` and manually running a `git clone` of this repo?

The `imports_build` directory is me trying to find an easier way to allow individuals to include or exclude builtins at compile time. I suspect the way I've designed that is incompatible with `go get`. Which is something I'll have to look into. But in the meantime a manual `git clone` _should_ pull in the directory hierarchy needed.

**Comment by lmorg** [comment]
@sebastien Which version of `go` are you compiling against?

**Comment by lmorg** [comment]
I've pushed an update that should (in theory) fix support for `go get`. Pragmatically though, `go get` is very difficult to run automated tests against. So I've updated the build instructions to suggest using `git clone` instead: https://murex.rocks/INSTALL.html

Given `go get` is no longer the official install method and, despite this, the fix I've also released, I'm going to close this issue. If you're still struggling to install via `go get` then I'd suggest following the `git` method in the INSTALL instructions (link above) or pulling one of the pre-built binaries from the DOWNLOAD page: https://murex.rocks/DOWNLOAD.html

Failing all that, please do open another issue in Github if any further investigation is needed on my part.

**Comment by sebastien** [comment]
Hi there, I confirm it's working, but here are a couple of suggestions. First the git clone command [there](https://murex.rocks/INSTALL.html) should be

```bash
git clone https://github.com/lmorg/murex $GOPATH/lmorg/murex
```

and then running `go build github.com/lmorg/murex` fneeds  both `bzr`and the ` GOVCS='*:git|hg|bzr'` -- which I think should be mentioned in the doc.

**Comment by lmorg** [comment]
Hi @sebastien 

`bzr` is only needed if you enable the `bson` optional type at compile time -- which is normally disabled precisely because of the `bzr` dependency. This is mentioned in the `bson` [include file](https://github.com/lmorg/murex/blob/master/builtins/imports_src/type-bson.go) and did appear in an earlier version of the [install doc](https://github.com/lmorg/murex/commit/ce957486e533e8c87bea4743f97b5cb367ce5b05#diff-09b140a43ebfdd8dbec31ce72cafffd15164d2860fd390692a030bcb932b54a0) but was removed to keep the document succinct. Thus a standard `go build` shouldn't require `bzr` nor `labix.org/v2/mgo` because that package isn't getting used. Yet `go` is still requesting it even though it's clearly not compiling it....

I suspect the issue might lie with `go.mod`. Looking there, the mgo package is listed as required. So I'll re-open this ticket and take a look at that.

Thanks for reporting.

**Comment by lmorg** [comment]
This whole issue is around one optional builtin data type: `bson`. The demand for that would be low so as tempted as I am to remove that builtin entirely, I've decided to try an alternative library instead. This one is newer, actively maintained, but also crucially (in the context of this particular issue) appears to be served via git.

Let's see if this is any improvement.

Change is due to be committed as part of v2.2 release -- pending change currently sat in `develop` branch

**Comment by lmorg** [comment]
Change merged into master
