### ISSUE TITLE
Fail if variable is missing

### ISSUE THREAD

**Issue by piegamesde** [lmorg/murex#380]
I am accessing an environment variable, and would like to fail with an error when it is not set. This could be ad-hoc or global like Bash's `set -u`.

**Comment by lmorg** [comment]
Good idea. I'll incorporate that feature into the next release.

**Comment by lmorg** [comment]
Update made to `develop`. Will be pushed to `master` with the next release, which pragmatically might be around Christmas time. If you need this feature more urgently then you'll need to build from `develop`.

At the moment it is opt. You can by the following command, set either inside your function scope or in `~/.murex_profile` if you want it global
```
config: set proc strict-vars true
```

This feature will potentially break scripts when enabled because it doesn't just print an error, it will fail the parameter parser meaning any command will not be executed if it has a parameter which is an unset variable. The appears to be the same behaviour as Bash and seems to be a sensible behaviour one should expect. So I copied that behaviour here too. eg

```
» config set proc strict-vars false
» out: This is $only a test
This is  a test
» config set proc strict-vars true
» out: This is $only a test
Error in `out` (1,1): variable does not exist
```

I'd quite like this option so I'm tempted to make it the default behaviour (ie you have to opt out if you don't want it) but I'm going to leave this as opt in for a release or two to allow time for any uncaught bugs to bleed out before I force it on everyone.

**Comment by piegamesde** [comment]
Many thanks, will try out soon(™)

> I'd quite like this option so I'm tempted to make it the default behaviour

Yes, please. Any language (except for shell-likes) fails if you use a variable that is not defined, and IMO this should be the default for any new programming language. Of course, transitioning to that default is complicated. If run-time warnings are a thing in Murex, adding some might be helpful.

One nit about the error message though: please also print *which* variable was unset and caused the error.

**Comment by lmorg** [comment]
> One nit about the error message though: please also print which variable was unset and caused the error.

Already ahead of you on that one: fd92b3f :)

**Comment by lmorg** [comment]
This has now been merged into `master`
