### ISSUE TITLE
Clarify C requirement

### ISSUE THREAD

**Issue by 89z** [lmorg/murex#415]
I tried building, and I get this:

~~~
PS D:\Desktop\murex-master> go build
# github.com/mattn/go-sqlite3
cgo: C compiler "gcc" not found: exec: "gcc": executable file not found in %PATH%
~~~

I checked the docs [1], and I dont see mention that C compiler is required.

1. https://github.com/lmorg/murex/blob/master/INSTALL.md#from-source

**Comment by lmorg** [comment]
Windows isn't well supported because there's all kinds of edge cases with how Windows handles CLI commands
* it doesn't decouple the terminal emulator and the shell it means you cannot rely upon STDIN working as expected
* it sends parameters as a single string rather than an array of strings. Which means breaks the way how quotation marks and escaping works. This is compounded by the fact that every application then has to handle it themselves so there's no universal standard for dealing with spaces in parameters etc.

For these reasons _murex_ is very much experimental on Windows and the recommendation is that you run it on WSL instead. In fact I've been tempted to drop Windows native support entirely rather than ship a shell I know is buggy. There are hints to that elsewhere in the docs but I definitely should make this warning more prominent. Sorry about that, I'll get those docs updated.

With regards to the C requirement, that's been documented in the changelog (https://murex.rocks/docs/changelog/v2.6.html) but, as you correctly stated, it should also be described in the INSTALL doc too. Sorry about that too -- I'll fix that too.

**Comment by lmorg** [comment]
sqlite3 is used by one of the builtins: https://murex.rocks/docs/optional/select.html
The point of _murex_ is that it's more than just a dumb terminal for forking executables. It's a richer programming environment that understands structured data like JSON and tables. However you can disable that builtin if you want:
```
# From murex's source directory
rm builtins/imports_build/optional-select.go
```
(or `del` if you're running Windows)

Then recompile the Go project the usual way: `go [ build | install ]`

As for why I use a C library rather than native Go, simply because the C library is better. It's a lot faster and the official source for sqlite3. In fact given how good sqlite3's code base is, I'd wager the C library has more tests and fewer bugs than any of it's Go counterparts. So on this occasion using the C library is pragmatically the right choice. Of course you might disagree that supporting sqlite3 at all is the wrong choice, but the `select` builtin is optional so you don't need to compile it if it's not to your tastes.

**Comment by lmorg** [comment]
Website updates: https://github.com/lmorg/murex/pull/416/commits/98ea05614cdc08cde646612466a239e3a6b40078

**Comment by 89z** [comment]
> It's a lot faster and the official source for sqlite3

Yeah but youre running SQL against `ps`:

https://murex.rocks/docs/optional/select.html

were not talking about gigabytes of input. Dont you think youre using a sledgehammer when a normal hammer would do?

**Comment by lmorg** [comment]
That's an example. I'm not going to load a multi-gigabyte file on the website as an example because that would be cruel to anyone who tried to load that page. However someone might want to parse gigabytes of input with this shell because shells are very good at doing that sort of thing since you getting streaming and parallelization for free. I've often needed to parse multi-gigabyte files and found the command line pretty effective in doing so. In fact it was this use case (parsing gigabytes of structured data, filtering and transforming it) that was the inspiration behind _murex_. So I've intentionally kept those possibilities in mind when designing the builtins.

I had weighed up the pros and cons of using sqlite3 heavily. It wasn't enabled by default for a number of releases because I wanted to avoid `cgo` if I could and had considered using a native Go library. But in the benefits sqlite3's C library adds is hard to ignore:
+ more unit tests (significantly more in fact. That library has more lines of code for tests than it does for everything else)
+ fewer bugs
+ better compatibility (it's the official sqlite3 source so there's no confusion about what is supported and what isn't)
+ more secure
+ much greater performance
+ more wide spread usage / more eyes on the code (so any issues will be spotted and resolved quicker)

sqlite3's code base is one of the best C code bases out there. So it's by far and away the best choice of sqlite3 libraries available. Not using it just because it's not Go is, frankly, short sighted given what really matters the most is how the compiled shell performs and not some intellectual pursuit of language purity. I use this shell personally every day and I don't want something half backed just because it's not written in C.

If `cgo` proves to be an issue then I'd recommend downloading _murex_ from either a package manager or directly from https://murex.rocks (which are up to date builds -- the CI build script is included in the project's git repo). Or, as I said above, you're welcome to disable that builtin entirely if it's not a feature you're likely to use. Failing all that, you're welcome to fork the project and replace mattn's excellent library with one of the other pure Go sqlite3 libraries. But at this point in time I'm 100% certain that the C library is the right choice.

**Comment by 89z** [comment]
> some intellectual pursuit of language purity

I dont care about that. What I care about, is not being able to build something, because the owner chose to create a project that uses multiple languages. My computer has a Go compiler, but it doesnt have a C compiler. I dont think its worth it for me to install a C compiler just to build one project. I respect your reasons, but maybe you could change the project somehow so that the C parts are **off** by default. Then people can enable them, if they want to. I think Go allows you to do that, with build tags combined with command line flag.

**Comment by lmorg** [comment]
> What I care about, is not being able to build something, because the owner chose to create a project that uses multiple languages. My computer has a Go compiler, but it doesnt have a C compiler. I dont think its worth it for me to install a C compiler just to build one project.

I do completely understand that some people don't want to install compilers and that's why I provide pre-compiled binaries for you. In fact INSTALL specifically recommends this approach over compiling the source yourself. So I see your argument here as moot.

> I respect your reasons, but maybe you could change the project somehow so that the C parts are off by default

I'm not turning the C parts off by default because they do add features to the shell. As I've said already, what matters the most is the UX of the compiled shell not the pain of having an additional compile time dependency. 

I've also already given you instructions about how to turn off the C parts (it's literally just one file you delete). So you already literally can turn that feature off if that's what you want to do.

I honestly don't understand the argument here. Everything you're asking to do you can already do.
