### ISSUE TITLE
Array's inner type is unreliable

### ISSUE THREAD

**Issue by Pascalio** [lmorg/murex#497]
It seems the old `a: [1..3]` and the new `%[1..3]` aren't equal there. The old one seems to produce arrays of str here where as the new one produces arrays of num (which is better). But this behaviour is broken when you type `%[1..3,4]`. It produces str instead...

![murex array type bug](https://user-images.githubusercontent.com/16581264/209690077-20710e07-b11b-4b5c-9858-67a0d07553ea.png)

Btw, is there a way to tag the type of an array? Something inspired by #484 ?

**Comment by lmorg** [comment]
Thanks for the bug reports

> It seems the old a: [1..3] and the new %[1..3] aren't equal there. 

`a` will always produce a list of strings. This was intended because a list of strings are easier to stream than (for example) JSON. So you could create super massive array and have other processes on the pipeline operate on that array concurrently while `a` is generating them.

...at least that was the original design decision. murex has evolved somewhat since those days and while it's still worth keeping _some_ support around for streaming super massive arrays, having that as the default behaviour is clearly not intuitive.

So what I might do is make `a` default to JSON arrays by default (even going as far as making `ja` an alias for `a`). `%[]` creates JSON arrays too -- so that will keep things a lot more consistent.

> But this behaviour is broken when you type %[1..3,4]. It produces str instead...

Yeah. That's a really cheap hack of mine. I'll look to get that changed

> Btw, is there a way to tag the type of an array? Something inspired by https://github.com/lmorg/murex/issues/484 ?

Currently no. Arrays aren't a primitive like numbers and strings are. Instead they a concept which can be represented by a number of document formats (such as JSON, YAML, lists of strings, S-Expressions, rows in a CSV table, etc). Which means the primitive type of an element in an array is unknown until you come to decode the document.

The original reason behind this stems from one of murex's core missions to support native Linux/UNIX command line tools without any additional setup/configuration. Which means all data types eventually get converted into byte streams, such is the limitation of POSIX pipes. But if murex can be intuitive enough then is should be able to emulate a rich variety of types without users every knowing -- or even caring -- that it is all just a hack on top of 50 year old technology.

Looking forwards, there is almost certainly a way I could implement support of tagging the type of array, but it would need some careful thought about how I'd implement it.

That all said, the original design of murex was based around making things "just work" regardless of the underlying data types. So if there are edge cases where array elements being incorrectly typed is causing unexpected behaviours then fixing those edge cases should be my first priority. It probably doesn't help here that expressions are strongly typed. So there's a couple of solutions here:

1. Go the Javascript route of having everything weakly typed and use `===` et al to perform additional type checks.
2. Keep murex expressions strongly typed and invent a murex specific syntax to auto type cast.

Both of these would be easy fixes but I'm a little torn which way to go. On the one hand, weakly typed programming languages have a plethora of bugs and edge cases due to things looking like one type but instead being another (eg credit card numbers that begin with a zero). So defaulting to strongly typed would help mitigate these. But on the other hand, expecting users to learn murex specific operators to solve common problems seems a bit of a reach.

...or maybe the 3rd option is to default to a weakly typed (eg so you can `"1" + 1`) but have a flag that you can set to switch expressions between weakly and strongly typed. This flag could be defined in `config` and default to weakly but allow people to enable strict types when they need the type safety?

**Comment by lmorg** [comment]
The more I think about that last point, the more I'm convinced that's the right approach. Make expressions weakly typed by default but it can be switched to strongly typed either via:

```
config: set proc strict-types true
```
(exact name of setting to be determined)

...or a prefix flag on the expression, eg

```
<s> "13" == 13 # false, strict types
<w> "13" == 13 # true,  weak types
```
(exact prefixes to be determined)

**Comment by lmorg** [comment]
I've knocked up a POC the strong/weak types:
![image](https://user-images.githubusercontent.com/12153701/209951351-85ef244c-30e2-40d4-951d-5aabf3de56a8.png)

Only multiply is currently supported and even that will need refactoring to to make the code cleaner. But it works as a demonstration

**Comment by Pascalio** [comment]
> `a` will always produce a list of strings.

Ok, I see!

> So what I might do is make `a` default to JSON arrays by default (even going as far as making `ja` an alias for `a`). `%[]` creates JSON arrays too -- so that will keep things a lot more consistent.

I lack perspective on this: I'll be happy whatever way you choose. 

The most important thing here was maybe that `%[1..3,4]` should produce numbers like `%[1..3]` does.

> Yeah. That's a really cheap hack of mine. I'll look to get that changed

So, that's perfect!

--------------------
Now, as to the question of types....

My gut reaction isn't very positive to the idea of introducing a weakly typed system like javascript's... This is however a bias of mine: I'm more on the "write-once, read-many" end of the line than the "write-many" one, so I think safety of scripts should come before conciseness. But if we can have both, it's brilliant. I'm not totally sure what implications your 3rd proposal of weak types would have, beyond the POC you showed above. Perhaps, it's all fine and safe.
Nonetheless, the initial problem was that 
`%[1..3,4] -> foreach n { ${$n + 1} }`
wasn't working, but now it's fixed (or is to be soon)

But still, it's important to know how to handle type mismatches... I am biased to think that strong types + a handy way to auto cast is best. But I'm not sure, I see the big picture.

Or maybe, as in your 3rd option, but defaulting to strong types, and a prefix to switch a line to weakly typed...

Sorry, not very incisive input. I'll be mulling it over a bit more.

**Comment by lmorg** [comment]
> I lack perspective on this: I'll be happy whatever way you choose.

I created a POC to change `a` to `ja` but it broke a whole bunch of tests. I'm still not against changing the default data type for `a` but I'm going to hold off that change for now because I fear I might be introducing too much change (even for a major release) if I were to alter that behaviour.

> The most important thing here was maybe that %[1..3,4] should produce numbers like %[1..3] does.

Agreed :)

-----

As for strong vs weak types. Generally speaking I do 100% agree. I'm just a little concerned I might be trying to make life unnecessarily hard by defaulting to strong types. One of my observations of PowerShell is that it's type system raises the barrier of entry above casual use and I don't want murex to fall into the same trap. Furthermore since all Linux/UNIX parameters and input/output streams are basically just strings anyway, I have the added problem that anything too strict could be a pain to use as you'd have to constantly remember to add manual type casting.

I wonder if a compromise here is to say expressions are always strongly typed (eg so `5 * "5"` would fail even when the shell is set to weakly typed) but variables and subshells are allowed auto-cast to a number if the shell is set to weakly typed.

eg

```
» i = 5 * "5"
cannot Multiply non-numeric data types at char 7
Expression: i = 5 * "5"
          :       ^
Symbol    : Multiply
Value     : ''
```
(^ fails even in weak mode because it is a syntax error)

```
» config set proc strict-types false
» i = 5 * ${echo 5}
```
(^ succeeds in weak mode because the STDOUT of that subshell is silently auto-cast)

```
» config set proc strict-types true
» i = 5 * ${echo 5}
Error in `expr` (0,1): cannot Multiply with String types at char 17
                     > Expression: i = 5 * ${echo 5}
                     >           :                 ^
                     > Symbol    : Calculated
                     > Value     : ''
```
(^ fails in strict mode because auto-casting is disabled)

```
» i = 5 * ${echo 5 -> cast num}
```
(^ succeeds in strict mode because you're manually casting)

I've implemented this behaviour into `develop` as a POC (currently works against `*`, `/`, `+`, and `-` operators only though) so we can have a play before deciding.

**Comment by lmorg** [comment]
Sorted the array problem:
![image](https://user-images.githubusercontent.com/12153701/210016051-7752d12a-f5f2-44c8-bb51-63f37a06612a.png)
Please note from the above that you still get a string array if you enter `01` instead of `1`. That's by design because "01" can't be correctly represented as an integer.

**Comment by Pascalio** [comment]
> I created a POC to change `a` to `ja` but it broke a whole bunch of tests so ended up reverting the change. I'm still not against changing the default data type for `a` (it actually a very easy change) but I'm going to hold off that for now

Sure!

> Sorted the array problem

Great!

> Generally speaking I do 100% agree. I'm a big fan of strongly typed languages. However in this particular instance I'm a little concerned I might be trying to make life unnecessarily hard by defaulting to strong types.

You're right. I currently fail to imagine how `5 * "5"` might be hazardous and it's certainly harder if it's disallowed... As long as you can't do `5 * "hi"` and such.

> I wonder if a compromise here is to say expressions are always strongly typed (eg so `5 * "5"` would fail even when the shell is set to weakly typed) but variables and subshells are allowed auto-cast to a number if the shell is set to weakly typed.

In other words, this weak typing POC could be defined as something like "activate syntactic sugar for numeric auto-casting subshells and variables." Makes it clear that it's only about defining this sugar:
`<num> <arithmetic> ${<str>} => <num> <arithmetic> ${<str> -> cast num}`
Right?

**Comment by lmorg** [comment]
Exactly that. The question is whether to extend that to comparison operators too. In fact it would only need to be greater than (or equal to) and the less than counterparts because there is already `~~` / `!~` operators which is a lazy match: converts everything to a lower case string and then compares. Theoretically, I could probably introduce `>~` / `<~` but I worry if that's ambiguous as to whether inclusive or exclusive (ie a `>=` counterpart or just `>`).

The consistent solution might be to replicate the weaker behaviour like the arithmetic operators but things get a lot murkier here because you can compare strings as well as numbers. Whereas with arithmetic you can make a relatively safe assumption that if it looks like a number then it should be treated as one, that rule is less reliable when it comes to comparisons.

I'm not really sure what the best option is here.

**Comment by Pascalio** [comment]
Hmm I'm not really sure either...
Let's try to find out what could go wrong if `==` does the auto-casting, won't we?
"string" == 5   => false 
"5" == 5   => true
We can't happen to compare a number and pointer to virtual memory because it's not that type of language...
I lack expertise in this, I'm sorry. 
To me, so far, it looks safe.

**Comment by lmorg** [comment]
The approach I've taken is rather simplistic:
- if the type matches then it will compare the values of that type
- if the types do not match then it will compare the value as strings

It does not check if the types both appear to be numeric, it just compares them as strings if the types do not match.

I'm not 100% sold this is a perfect solution but it is a good starter and I can always improve the logic if any problems are highlighted.

**Comment by Pascalio** [comment]
Sounds safe to me!
I'll close it then since all questions are for now solved.

**Comment by lmorg** [comment]
@Pascalio 

I appreciate this is a closed issue, but I thought I'd share an update I'm working on in `develop` since it relates to our language design discussions.

Currently the only way to access elements inside an array or object is via `[]`. Which can lead to some pretty painful REPL code. The reason `[]` was born was because originally everything was a pipeline. Thus you'd `$variable -> [ property ]`. The `$variable[property]` came a little latter but is literally just syntactical sugar for the former method.

With all the work I've done rewriting the parser based on our conversations, this has opened the door to some new improvements with variable handling too. So no you can access properties directly via `.` notation. eg

```
# create object
» bob =%{foo: bar, hello: world}
» $bob
{
    "foo": "bar",
    "hello": "world"
}

# alter value of /hello in $bob
» bob.hello = "lmorg"
» $bob
{
    "foo": "bar",
    "hello": "lmorg"
}

» echo $bob.foo 
"bar"
```

(This is still very beta though so I'm expecting a boat load of bugs)

---

The idea behind this change is that:
* `[]` notation will be immutable. So you can have a bunch of macros, like being able to select multiple elements, being able to use variables to reference element names, and a few other ideas I've got planned)
* `.` notation will be mutable. So you can alter the values held within but it is a lot stricter about how you access elements because of this

**Comment by lmorg** [comment]
`alter` does still offer something in that you can merge entire objects together. But it's absolutely terrible for simple changes to properties. That said, it would be possible for me to create a new operator that could merge, eg
```
» foo = %{ a: 1, b: 2, c: 3 }
» foo <~ % { z: 26, y: 25, x: 24 }
» $foo
{
    "a": 1,
    "b": 2,
    "c": 3,
    "x": 24,
    "y": 25,
    "z": 26,
}
```

The `<~` token used in the example is just something to illustrate this idea. I'm not suggesting that should be the token that we actually use.
