### ISSUE TITLE
What is the level of support for Windows?

### ISSUE THREAD

**Issue by runeimp** [lmorg/murex#604]
**Describe the problem:**

It is next to impossible to determine that Murex supports Windows, but I _think_ I saw a reference to it "being a thing" somewhere. Does it work fully in Windows? Works but most built-ins you'd find in Bash are missing? Or ???

**Possible ways to implement:**
I would love to find a Go based bash like shell that was truly cross-platform for a few projects I'm planning

**Additional context:**

**Documentation:**
Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [x] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

[add any additional detail, this will help us to write better docs]
If Murex really does support Windows that needs to be made MUCH clearer in the docs.  😉

**Comment by lmorg** [comment]
I agree the docs are really unclear. The main reason for that is that none of the contributors run Windows. So while the code is written to support Windows it's not the easiest platform for us to test on. There are other known limitations as well, which is documented here: https://github.com/lmorg/murex/blob/master/docs/FAQ.supported-platforms.md

That used to sit on the main website too. I'm not sure why that has disappeared but I can get it added back in.

**Comment by runeimp** [comment]
So no coreutils yet. That too bad. Yeah, I know it's a problem. Lots and lots of commands. But I do use `head`, `tail`, `cut`, `grep`, and `tr` _all of the time_. If I don't have those it's almost useless for me personally. I'd love to contribute to that effort though.

I mostly hate Windows but I believe cross-platform shouldn't be that big a deal (for most things), at the least with Linux, macOS, and Windows. I know "it's not that simple" but I think the effort is generally worth it. I wish OS/2 and BeOS was still a thing too really. But I do have a Windows 10 system for gaming mostly and the odd cross-platform testing. I'll see about setting it up testing again. Or just running a VM on my MBP for testing again.

**Comment by lmorg** [comment]
> So no coreutils yet. That too bad. Yeah, I know it's a problem. Lots and lots of commands. But I do use `head`, `tail`, `cut`, `grep`, and `tr` all of the time. If I don't have those it's almost useless for me personally. I'd love to contribute to that effort though.

I did start creating my own coreutils package but I recently scraped all of that code because it is a _massive_ development overhead and would still be a source for so many incompatibilities (which coreutils behaviour would you model this after? BSD can differ from one OS to another and GNU is massively different again).

Plus there are already a number of ways to get cureutils on Windows:
- WSL (the method I recommend)
- Cygwin (https://cygwin.com)
- msys2 (https://www.msys2.org)
There's also a lot of good content to read up on this at https://www.mingw-w64.org/

In addition to the above, there are a number of projects already rewriting coreutils in memory safe languages like Rust and Go.

And then there's the "one binary distributions" (for want a better description)
- BusyBox (https://www.busybox.net)
- U-Root (https://github.com/u-root/u-root)
As an aside, I had recently reached out to the u-root developers for a collaboration: https://github.com/u-root/u-root/issues/2676

I use coreutils heavily too but I've found Murex's builtins do already satisfy a lot of common use cases for coreutils. The Murex builtin counterparts are named differently because the aren't built to be backwards compatible with (for example) `grep`. Instead Murex builtins are built to be intelligent about structured data. For example `grep` would mangle a JSON document whereas the Murex counterpart, `regexp`, would return valid JSON if the input type was JSON (and valid TOML, YAML, CSV, S-Expressions etc if the input type was any of them too).

> I mostly hate Windows but I believe cross-platform shouldn't be that big a deal (for most things), at the least with Linux, macOS, and Windows. I know "it's not that simple" but I think the effort is generally worth it.

I agree, that's why Windows is a build target. But without people testing and filing bug reports for Windows, it's going to be hard to argue that the Windows builds are stable. Particularly when Windows does introduce a number of quirks (as detailed in the link I shared).

> I wish OS/2 and BeOS was still a thing too really.

BeOS lives on via Haiku but that project isn't too relevant these days https://www.haiku-os.org 

BeOS was frekin awesome though.

**Comment by runeimp** [comment]
Yeah, there are ways to get coreutils on Windows. But the point for my couple of projects is that they install **one** binary and are good to go. If I find a good Go based coreutils though that could be a thing. I really do like Murex.

**Comment by lmorg** [comment]
To be fair, I am open to the idea of having a Murex coreutils package (one of the original scopes for Murex was to provide a "busybox" like experience). The way builtins are linked against in Murex does make it very easy to include and exclude specific builtins for specific platforms (eg include Murex coreutils for Windows but exclude it on POSIX-like platforms).

The problem I face with building a Murex coreutils package isn't the limitation of Murex's modularity, it's simply just a lack of contributors. Building a coreutils package in addition to supporting the core language and interactive shell would be impossible for me alone. But I'm more than open to having other contributors writing code towards coreutils.

There isn't any docs describing the core APIs for writing builtins, so I'd need to write them up to assist. But if you're comfortable writing code in Go and fancy contributing to Murex then I'd gladly accept any pull requests. In theory you should also be able to have the Murex coreutils as a separate git repository that we reference at build time (either via git submodules or using Go's own package importing mechanisms) so there isn't even a hard requirement that any additional Murex builtins be part of the main Murex project -- just in case you fancied having an experiment with writing your own builtins but wasn't ready to commit to any significant levels of contribution.

I'll get some docs written on how to write Murex builtins regardless though.

**Comment by kmatt** [comment]
[BusyBox](https://frippery.org/busybox/) has been "close enough" for me in most cases on Windows 10. While not being a Go binary, its a simple install. [Git for Windows](https://gitforwindows.org/) also supplies many coreutil ports.

Would it make any sense to support a Murex configuration for Windows that says "My coreutils binaries are at this path" ?

**Comment by lmorg** [comment]
@kmatt yes. That's a very good idea

**Comment by kmatt** [comment]
I'm only now just starting to use Murex on Windows 10, using https://jmeubank.github.io/tdm-gcc to build the SQLite3 dependency build within `go build`.

Interestingly when in Powershell, `which grep` shows me the expected path within `C:\Program Files\Git\usr\bin.grep.exe`.

But within Murex, that resolves to `/usr/bin/grep` where `ls /usr/bin` appears to have the Git for Windows coreutils .exe's 

How does Murex "know" to expose `/usr/bin` ? My .murex_preload and .murex_profile are empty.

**Comment by lmorg** [comment]
Murex pulls all that data dynamically. So what you’re seeing there is the environment as presented to Murex. 

What do you get if you run `os`?

**Comment by kmatt** [comment]
```
murex » os
windows

murex » which grep
/usr/bin/grep
```

In PowerShell:

```
~> which grep
C:\Program Files\Git\usr\bin\grep.exe
```

**Comment by lmorg** [comment]
That is very weird. Are you able to share your environmental variables? eg
```
$ENV
```
take care to redact anything that is sensitive

I'll then see if I can emulate your environment from that

**Comment by kmatt** [comment]
> That is very weird. 

I should note this is a fresh build of v4.2.5110 and so far is working well for the basic shell commands I have tried, and is providing a Linux-like shell experience on Windows 10 by using the Git for Windows coreutils.

For example `ls -la` works, I type that in PowerShell constantly because of muscle memory from spending more time in Linux shells (`-la` not valid on PS).

Thus this is curiosity about configuration on Windows. Will be spending more time in it, happy to test things.

> Are you able to share your environmental variables?

Heavily redacted:

```
murex » $ENV
{
    "ALLUSERSPROFILE": "C:\\ProgramData",
    "APPDATA": "C:\\Users\\mkeranen\\AppData\\Roaming",
    "COLUMNS": "140",
    "ComSpec": "C:\\Windows\\system32\\cmd.exe",
    "CommonProgramFiles": "C:\\Program Files\\Common Files",
    "CommonProgramFiles(x86)": "C:\\Program Files (x86)\\Common Files",
    "CommonProgramW6432": "C:\\Program Files\\Common Files",
    "DriverData": "C:\\Windows\\System32\\Drivers\\DriverData",
    "EXE4J_JAVAJ_HOME": "C:\\Program Files\\Java\\jre1.8.0_361",
    "GOPATH": "C:\\Users\\mkeranen\\go",
    "HOMEDRIVE": "C:",
    "HOMEPATH": "\\Users\\mkeranen",
    "LOCALAPPDATA": "C:\\Users\\mkeranen\\AppData\\Local",
    "NUMBER_OF_PROCESSORS": "12",
    "OS": "Windows_NT",
    "PATHEXT": ".COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.CPL",
    "PROCESSOR_ARCHITECTURE": "AMD64",
    "PROCESSOR_IDENTIFIER": "Intel64 Family 6 Model 154 Stepping 4, GenuineIntel",
    "PROCESSOR_LEVEL": "6",
    "PROCESSOR_REVISION": "9a04",
    "PSModulePath": "C:\\Program Files\\WindowsPowerShell\\Modules;C:\\Windows\\system32\\WindowsPowerShell\\v1.0\\Modules",
    "PUBLIC": "C:\\Users\\Public",
    "Path": "C:\\Users\\mkeranen\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\mkeranen\\go\\bin;C:\\Users\\mkeranen\\.dotnet\\tools;C:\\Users\\mkeranen\\Python\\Python310;C:\\Users\\mkeranen\\bin;C:\\Users\\mkeranen\\scripts;C:\\Program Files\\Git\\bin;C:\\Program Files\\Git\\usr\\bin;C:\\Users\\mkeranen\\bin\\TDM-GCC-64\\bin",
    "ProgramData": "C:\\ProgramData",
    "ProgramFiles": "C:\\Program Files",
    "ProgramFiles(x86)": "C:\\Program Files (x86)",
    "ProgramW6432": "C:\\Program Files",
    "SHELL": "C:\\Users\\mkeranen\\go\\src\\github.com\\lmorg\\murex\\murex.exe",
    "SystemDrive": "C:",
    "SystemRoot": "C:\\Windows",
    "TEMP": "C:\\Users\\mkeranen\\Temp",
    "TMP": "C:\\Users\\mkeranen\\tmp",
    "TZ_LIST": "America/Denver,SLC;America/New_York,MCO;UTC",
    "USERNAME": "mkeranen",
    "USERPROFILE": "C:\\Users\\mkeranen",
    "WSLENV": "WT_SESSION::WT_PROFILE_ID",
    "ZES_ENABLE_SYSMAN": "1",
    "windir": "C:\\Windows"
}	
```

**Comment by lmorg** [comment]
I think i can see what is happening here. `which` is part of the GNU tools installed by git (or whatever) rather than something Murex is seeing. So if you were to do something like:
```
ls -l ${which grep}
# this would expand out to:
# ls -l /usr/bin/grep
```
you'd get a file not found type error.

I'd been mulling over the idea of writing a `which` builtin to represent Murex's view of the world. If the above command does produce an error then that adds weight to the need for `which` to be a built in.

**Comment by jcrben** [comment]
If people launch murex from inside bash on windows (shipped with Git-for-Windows, known as "git-bash"), they'll likely just get all that stuff. I'm on my personal (Linux) machine, not a work machine, so can't test it right now
