### ISSUE TITLE
Mid-file fuzzy autocomplete like zsh

### ISSUE THREAD

**Issue by gcv** [lmorg/murex#619]
**Describe the problem:**

It would be great if Murex supported mid-file autocomplete like zsh, and optional fuzzy support would be great, too. So from the murex source tree, I could type `ls _test`, hit Tab, and autocomplete would suggest files like `benchmarks_test.go`, `defaults_test.go`, etc.

**Possible ways to implement:**

I have not looked into the Murex readline or autocomplete implementation closely enough to give advice.

**Documentation:**

Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [X] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

**Comment by lmorg** [comment]
You can do fuzzy autocompletions by pressing `[ctrl]`+`[f]`: https://murex.rocks/docs/user-guide/terminal-keys.html#ctrlf-find-in-autocomplete-suggestions

I might be able to incorporate this as a `[tab]` as well but that would be a more difficult change due to how autocompletions are compiled.

Before I do though, can you have a play with `[ctrl]`+`[f]` and see if this is ergonomic enough already (Murex's fuzzy find does come with a few added features too)

**Comment by gcv** [comment]
Thanks, that's interesting. I tried Ctrl-F. It's definitely a step in the right direction, and might be a reasonable alternative. One difference is that it automatically recurses into subdirectories. This might or might not be desirable, depending on circumstances.

One behavior I ran into that might qualify as a bug is if I type `ls -l _test` then hit Ctrl-F, Murex says `partial word match` and does not let me Backspace. I have to use arrow keys to move around and deletion does not seem to work until I get to the next input.

**Comment by lmorg** [comment]
@gcv 
> Thanks, that's interesting. I tried Ctrl-F. It's definitely a step in the right direction, and might be a reasonable alternative. One difference is that it automatically recurses into subdirectories. This might or might not be desirable, depending on circumstances.

You can disable this behaviour with
```
config set shell recursive-enabled false
```
I quite like it because you can quickly traverse larger directory hierarchies without needing to remember the entire hierarchy (like with fzf). It also works against object hierarchies too. eg
<img width="674" alt="image" src="https://github.com/lmorg/murex/assets/12153701/eefc1236-7c28-4168-a09c-0ca8dad1a5f7">

> One behavior I ran into that might qualify as a bug is if I type ls -l _test then hit Ctrl-F, Murex says partial word match and does not let me Backspace. I have to use arrow keys to move around and deletion does not seem to work until I get to the next input.

That's because ctrl+f starts a new prompt. ctrl+f is a filter on the `[tab]` auto-completion results. If you type search terms you can see it appears in blue below readline:
<img width="674" alt="image" src="https://github.com/lmorg/murex/assets/12153701/747855d3-8706-409d-83cf-0ec6eda96269">
So you'd need to hit ctrl+f before putting your partial term like `_test` into readline.

*...at least that is how it currently works...*

It is definitely possible to add a feature that allows you to backspace readline values if the ctrl+f filter is empty. Thus if you were to ctrl+f a bit late in the autocomplete lookup, you don't have to `[esc] [bs] [bs] [bs]` ... `[ctrl+f]`

**Comment by gcv** [comment]
Interesting! I think I'll close out this ticket, at least for now. I'll re-open or ask for something more specific I can think of it. Thanks for the information and help.

**Comment by lmorg** [comment]
Any time :)
