### ISSUE TITLE
autojump with jump - need help

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#635]
This is not a bug, nor a feature request.

just my current status in trying to implement an integration with [jump](https://github.com/gsamokovarov/jump) an autojump command built in golang.

I am unfortunately stuck, calling for help.
What am I doing wrong?! 
I have added my questions/comments in the code below

If I may request just a few tips so I understand what I am doing wrong,
Thank you

```
function j (p:str [""] "path-to location") {
    if { $p } then {
        dir = ${ jump cd "$p" }
        if { $dir -> f +d } then {
            cd "$dir"
        }
    }
}

config: set shell post-prompt-func {
    # What if another script already has a post-prompt-func? how to gently overload it?
    # does the return value of this function affects exitnum?
    jump chdir
}

# doesn't work
autocomplete set "j" { [{
    "AnyValue": true,
    "AllowMultiple": true,
    "ExecCmdline": false,
    "Dynamic": ({
       # I can't get this code to work, first I am trying to get j's <parameter>
       # then it doesn't print the list of possible path
        ${jump hint <stdin>}
    })
  }]
}
```

**Comment by lmorg** [comment]
Just having a play with this at the moment. I think you're right that pre and post prompts should be events so that you can add several to them.

**Comment by lmorg** [comment]
Some feedback. This now works, but requires the latest version in `develop` (4.3.3000 or above).

The source file is: https://github.com/lmorg/murex-module-jump/blob/master/jump.mx

Sone notes from your code:
```
1 function j (p:str [""] "path-to location") {
2    if { $p } then {
3        dir = ${ jump cd "$p" }
4        if { $dir -> f +d } then {
5            cd "$dir"
6        }
7    }
8 }
```
1. The default value is an optional field so you don't need to include `[""]` in line 1
2. Murex tokenises variables rather than expanding them into the command line. This means that spaces are handled gracefully (like in "normal" programming languages) so you don't need to put variables inside quotation marks on line 3 and 5.

Aside from that, your code there works well.

---

```
config: set shell post-prompt-func {
    # What if another script already has a post-prompt-func? how to gently overload it?
    # does the return value of this function affects exitnum?
    jump chdir
}
```
1. you're right, another script would overwrite `post-prompt-func`. So I've removed that from `config` (normally I try not to break backwards compatibility but since `post-prompt-func` was only added in the previous version, I think I'm safe to break compatibility here by removing it again. It is now an event: `event: onPrompt jump=completion { ... }`
2. the return value of any `config` func or `event` wouldn't affect `exitnum`

My revised code here looks like this:
```
event: onPrompt jump=completion {
    jump chdir
}
```
Basically your code worked, but your points were correct about `config` being the wrong place for those functions. So my code here just reflects the change to Murex I've made based on your comments.

---

```
# doesn't work
autocomplete set "j" { [{
    "AnyValue": true,
    "AllowMultiple": true,
    "ExecCmdline": false,
    "Dynamic": ({
       # I can't get this code to work, first I am trying to get j's <parameter>
       # then it doesn't print the list of possible path
        ${jump hint <stdin>}
    })
  }]
}
```

1. To get `j`s parameter you need `$PREFIX` rather than `<stdin>`.
2. Also you didn't need the subshell `${}` either, but that wouldn't have broken anything. It was just superfluous.

The reason your code didn't work was because readline filters it's autocomplete suggestions to match the partial term. It wasn't designed for doing fuzzy matching outside of `ctrl+f`. This is where I've put another new feature in: `IgnorePrefix`

```
autocomplete set j %[{
    IncDirs: true
    Dynamic: '{ jump cd $PREFIX }'
    IgnorePrefix: true
    ListView: true
}]
```

What this is doing is:
* `IncDirs` means you get the benefit of Murex's directory completions as well as jumps
* `Dynamic` basically the same as your code except the use of `$PREFIX`. I've used `jump cd` rather than `jump hint` but I honestly cannot tell the difference between the two from my limited usage
* `IgnorePrefix` allows autocompletions from `Dynamic` and `DynamicDesc` to start with a term other than what has already been partially typed into the terminal
* `ListView` is purely an aesthetic thing. I think it looks better with `j` than the gridded view

You'll notice the format is slightly different there too:
1. `%[{ ... }]` instead of `{ [{ ... }] }` -- this is due to `%[]` being added recently: https://murex.rocks/docs/parser/create-array.html and since it converts the data into JSON, it means we can get away with a few other boilerplate noise:
2. quotation marks become optional (kept in for `Dynamics` value because we don't want the `$PREFIX` variable prematurely expanded
3. commas are redundant because we already know a new list item by the new line

I'd like to think that's a lot cleaner to read but since it's pretty new, you'll find a lot of example code is still using the old format.

---

```
autocomplete set jump %[{
    DynamicDesc: %({ jump --help -> tabulate --key-value --map })
}]
```

This is a new addition and it just parses the help page for `jump` and then converts it into an autocompletion hint

---

```
#${autocomplete get j} ~> ${autocomplete get cd} -> autocomplete set cd
```

This is commented out but what it does is take the autocompletion config for `j` and merges it into the autocompletion config for `cd`. The reason it is commented out is because I wanted to beta test `j` for bugs before integrating it into `cd`.

---

As you'll see from the link (https://github.com/lmorg/murex-module-jump/blob/master/jump.mx) i've turned that code into a module. so you can import it with this one liner:
```
murex-package install https://github.com/lmorg/murex-module-jump.git
```
This will download and install it

**Comment by orefalo** [comment]
Thumb up Laurence,
I wasn't expecting that much efforts into my initial request.
I have yet a lot to learn about murex,
Thanks a bunch for providing all these details and fixing the script.
We now have an auto-jump for murex!

Thank you
