### ISSUE TITLE
Aliases with | or #

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#692]
**Describe the bug:**

Reporting issue, I am having with the `alias` command

First I am having an issue sequencing multiple commands under one alias?
`alias update=brew update;brew upgrade;brew autoremove;brew cleanup; pnpm update -g`

Next, might be for the same reason.. The alias is not properly set when there is a `|` or `->`
`alias dpi=docker images | docker-color-output`

Looks like alias evaluates the line.. this should not happen until the alias is run
```
murex » alias dpiarch=docker image inspect --format '{{.ID}} {{.RepoTags}} {{.Architecture}}' ${docker image ls -q}
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
Error in `docker` (0,2): exit status 1
```

is there anything I missed on the docs?

**Comment by lmorg** [comment]
The line is fully evaluated and stored as an array. I didn't want `alias` to be yet another subshell because subshells are slow and we already have `function` which performs that role.

You can see their naked data structure in `runtime --aliases` (incidentally, it looks like I'm not storing `FileRef` data alongside aliases yet -- I'll have to fix that).

**Comment by lmorg** [comment]
Just to add, this also means you cannot use variables, nor any other shell-generated dynamic content, in your alias.

Aliases in Murex are true aliases -- just hardcoded pointers to another command. Whereas in Bash they're more like macros

**Comment by orefalo** [comment]
Hi again,

thank you for the details - it's clear, and functions can work.  I can document it once, I fully understand how to use them.

At this point, I am still having an issue..  I can't get them to output anything on stdout. 

```
murex » docker images | docker-color-output
REPOSITORY   TAG   IMAGE ID   CREATED   SIZE
murex » alias nono=function ii { docker images | docker-color-output }
murex » nono
murex » function hw { out "Hello, World!" }
murex » hw
Hello, World!
murex »
```

**Comment by lmorg** [comment]
it's just
```
function ii {
    docker images | docker-color-output
}
```
like how `alias` and `function` are different commands in Bash et al too.

The reason your code isn't working is because you're creating an alias that, whenever ran, will create a function.

**Comment by orefalo** [comment]
I see.. aliases are used as `alias` to function names.
   The best with can do with them, is calling a command, built-in, function with parameters.

This is very different from other shells indeed.

**Comment by lmorg** [comment]
yeah. Their usefulness is pretty limited. But that's intentional. It takes far less computation time calling an alias like this, which means things like `echo` can be an alias for `out` and you're not worried about subshells getting created for common operations, or having to additional layers of parsing, etc.

Also since aliases are all global in scope, you don't really want to be using them in scripts, it's really more just a "shortcut" or "symlink" type thing for the interactive terminal. So functions and privates offer greater power.

there is also another feature, completely undocumented, that might work. It's prompt variables. Basically the interactive prompt supports additional types of variables, prefixed `^`, that are ostensibly macros which parse your history file. the one you might be interested in is `^#`. eg write a pipeline
```
echo foobar | grep foo #example
```
then as your next command write `^#` and press [tab] after. you should have a `^#example` completion. run that and your `^#example` gets substituted for the above command line

**Comment by orefalo** [comment]
closing as resolved -
  expect a pull req from me to summarize the above in the docs
