### ISSUE TITLE
Binary size

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#715]
**Describe the query:**
So yesterday, while troubleshooting, I figured that Murex is 18MB.

Compared to other shells which typically land < 2MB, it's impressively over weighted.

Was wondering if you had any idea as to 

1. why is the binary so large?
2. ways to reduce it

**Comment by lmorg** [comment]
Go binaries are large because they include the runtime environment in the executable. Think like what Bash would be like if it included libc in its executable. Or how big the Python and Java runtimes are.

It's also worth noting that Murex is very much a "kitchen sync" of shells. eg Bash doesn't have JSON, TOML, CSV, etc parsers. Nor does it bundle a bunch of coreutils like Busybox.

As for reducing the file size, there are a few possibilities I have considered but all of them have drawbacks. Given that Murex is designed for more modern systems anyway (eg it defaults to 64 bit floating points) I can't really see it being used for the kind of low footprint machines that the like of Busybox are. So 18MB vs 2MB isn't going to be impactful.

I'll probably come back to file sizes at some point but personally I'd see that as more of a distraction at this stage vs tweaking the UX and improving performance

**Comment by orefalo** [comment]
> I'll probably come back to file sizes at some point but personally I'd see that as more of a distraction at this stage vs tweaking the UX and improving performance.

Agreed


I am not a Go expert, just have light notions - was wondering if an env such as https://tinygo.org/ could help.

**Comment by lmorg** [comment]
My suspicion of sqlite3 was bang on. Switching to a pure Go library shaved 6MB from the file size. The automated builds will still prefer the C version of sqlite3, if just because it's more battle tested. But custom builds will now default to using a pure Go version.

**Comment by orefalo** [comment]
Closing - was just trying to raise awareness.

IMHO, even with 6MB less , Murex is still seriously overnighted...
 I mean, it won't get skinny like the C based shells, but 5-6MB should be the lean spot.
