### ISSUE TITLE
fg/bg bug

### ISSUE THREAD

**Issue by orefalo** [lmorg/murex#716]
**Describe the bug:**

```
➜  bg { sleep 10000; out nono }
✦ ➜  jobs
PID  State      Background  Process  Parameters
501  Executing  true        exec     sleep 10000
✦ ➜  fg 501
✦ ➜  jobs
PID  State      Background  Process  Parameters
501  Executing  true        exec     sleep 10000
✦ ➜  fg 501
✦ ➜  jobs
PID  State      Background  Process  Parameters
501  Executing  true        exec     sleep 10000
✦ ➜
```

I would expect `fg` to bring back sleep in the front and block on it

**Comment by lmorg** [comment]
Thanks for the report. I'll pick this up for v5.1

**Comment by orefalo** [comment]
On a similar topic
```
STDIN:  0 bytes read / 0 bytes written
STDOUT: 3.61 KB read / 0 bytes written
STDERR: 0 bytes read / 0 bytes written
(murex functions don't currently support being stopped)
```

The is a huge limitation. Hope it can get solved.

**Comment by lmorg** [comment]
it's a _massive_ piece of work solve, but I'm in a much better place to solve it now than I was a few years ago (when that message was originally written)

The problem is that Murex doesn't `fork()` itself to run builtins (intentionally because there as several benefits in not doing so) but that means I cannot use the kernel to stop processes. So I now have to emulate that behaviour in user space. I've got the basic scaffolding in place to implement this though.

**Comment by orefalo** [comment]
Exactly, and beyond `starting, pausing and resuming`, processes give a sealed wrapper (especially for resources) which when killed doesn't alter the current space.

Now the key question: is it better to use a "process" toolbox or to rebuild it from scratch - and for what benefits.

**Comment by lmorg** [comment]
> I genuinely believed that you had implemented it.

It works fine for external commands

> Now, the crucial question arises - is it preferable to utilize a "process" wrapper offered by the operating system or rebuild it entirely from the ground up? And what advantages does each approach offer?

That what I discussed above. :)

I don't really want to fork every builtin. It might solve a lot of problems but it would also be slower and, at this stage of Murex's life, a step backwards. That might mean I'd have to write a sizeable chunk of user space code to emulate the kernel stopping a job, but as long as the behaviour is the same then I don't really think it matters that it is a user space hack.

**Comment by orefalo** [comment]
agreed that not all builtin need to be processes.

I was thinking about plus/minus comparing the two approaches.
besides speed, what other benefits do you get with threads that processes don't give you?

**Comment by lmorg** [comment]
It's a hell of a lot easier to pass around type annotations. Which is why I originally opted for thread rather than processes

**Comment by lmorg** [comment]
@orefalo just pushed some revised code to `job-control` branch that fixes some of the `fg`/`bg` issues. I'll likely merge into `develop` this week.

For v5.2 I'm also going to include some code that allows you to ^z to background builtins. Albeit it wouldn't stop those jobs like ^z would for UNIX processes. But it is a step towards implementing support for that.

**Comment by orefalo** [comment]
Thank you for the heads up Laurence, to be honest - it's a missing feature which forced me to put murex adoption on the side.

**Comment by lmorg** [comment]
You should have said! I'd have bumped the priority. Instead I've been playing around with some UI features like:

## inlining man pages

<img width="1776" alt="image" src="https://github.com/lmorg/murex/assets/12153701/9bebfcca-f64f-4985-942b-99320e16633a">

## interactive command line previews

<img width="696" alt="image" src="https://github.com/lmorg/murex/assets/12153701/3e8a1e3a-cca7-4401-b604-8357160b5263">

The idea of this latter feature is so that you can quickly query and debug command lines without having to constantly rerun the pipeline. This is particularly useful if trying to walk through a structure (eg JSON) that you're unfamiliar with. Particular when returned from a HTTP GET request / AWS CLI / etc that might take a while to call (since each commands output is cached)

No docs written on this yet but will follow ahead of the v5.2 release.

**Comment by lmorg** [comment]
@orefalo `develop` branch now has a rewrite of job control. This resolves the following issues:
1. builtins now support being suspended
2. `bg { ... }` functions now support `fg`
3. the rewrite also fixes a number of bugs where `bg` or `fg` didn't quite behave as expected with external processes

I'd still class this as experimental but even without taking that caveat into account, this is a _massive_ improvement compared to what was there before.

**Comment by lmorg** [comment]
@orefalo this has been merged to `master` and released

**Comment by orefalo** [comment]
Sorry, I didn't get a chance to try - busy with work.

**Comment by lmorg** [comment]
That's fine. I've done some testing of my own and it's there for if/when you're ready :)
