### ISSUE TITLE
Cursor flickering on backspace while having tab completion active on some terminal emulators

### ISSUE THREAD

**Issue by tsmish** [lmorg/murex#744]
**Describe the bug:**
In order to reproduce this, you'll need to type a known command, delete some characters at the end and press tab to enter tab completion. While the completion window is open press backspace. Cursor will rapidly go two spaces back and one space forward. 

**Expected behaviour:**
I want the cursor to go one space back directly.

**Screenshots:**
I attached [two asciinema screencasts](https://github.com/lmorg/murex/files/12772919/backspace_bug.zip) (make sure number of columns is somewhat near 69-127). I edited one of them to add 1 second delay between relevant entries so it is possible to see what I'm going on about on unaffected terminals. 

**Platform (please complete the following information):**
 - OS:  `Linux akiha 6.1.0-11-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.38-4 (2023-08-08) x86_64 GNU/Linux`
 - Terminal Emulator: foot, can also reproduce on xterm, can't reproduce on konsole and gnome-terminal
 - Murex version: v5.0.9300

**Additional context**
So, look at entries with timestamps 8.34699 and 8.352435 in unedited screencast (it is a list of json entries). First one comes from [echo](https://github.com/lmorg/murex/blob/09c2f4ad088208ccbc6f28f0450cbb73a0d427f0/utils/readline/write.go#L25). Second one I think comes from [clearHelpers](https://github.com/lmorg/murex/blob/09c2f4ad088208ccbc6f28f0450cbb73a0d427f0/utils/readline/write.go#L178). 
First entry has `\u001b[1D` at the end which causes cursor to go backwards one space too much before getting corrected by `\u001b[13C` at the end of the second entry.
That `\u001b[1D` is caused by [this line](https://github.com/lmorg/murex/blob/09c2f4ad088208ccbc6f28f0450cbb73a0d427f0/utils/readline/write.go#L79), commenting it out solves the problem.

I think the reason it's not reproducible on all terminals is because these entries come in rapid succession and some terminals are not fast enough to render them as two separate commands. 

There is also a similar problem with deletes in the middle of the string. It renders the entire string before jumping back to edit point which is kind of expected with this implementation, but causes flickering. (yay, multiple bugs in one report)

I suggest adding buffering to print in write_tty.go, so echo and clearHelpers output comes to stdout as one write instead of two. You can also make them return strings and combine them before printing, but that's hard to do without major changes to the codebase. I made a proof of concept and it does solve both of the problems I pointed out (even without commenting that line in echo).

**Comment by lmorg** [comment]
I've seen this happen on iTerm on macOS as well. I _think_ I know what the issue is (the logic switching between 'insert' and 'replace' mode, where the cursor needs to be in different positions, isn't being tested at all places of the code causing one of those often talked about off-by-one errors. I had tried to put a fix in place in 4.x but that fix then broke other things so I had to quickly revert it out again.

As an aside, I definitely need to be more testing here. I had started writing my own terminal emulator emulator (mock terminal emulator? dummy terminal? Not really sure the best name for this) for that purpose but that's legitimately a whole new project in itself so the work is still pretty rudimentary.

Going back to your issue, I think the issue here is compounded by the spell checker running in a separate thread. This means readline will print your command line, while spellchecking is working, then reprint the command line with the output from the spell check. As insane as that sounds, it did actually reduce flicker and made the command line feel snappier. But I'm certain there's plenty of optimisations that can still be made here.

I'm in the process of rethinking how syntax highlighting works so will definitely take a look at this as well.

However in the meantime, can you check if you still see the flicker if you turn off the spellchecker?
```
config set shell spellcheck-enabled false
```
There might be some quick wins I can achieve here just by revisiting how spell checking is forked.

**Comment by tsmish** [comment]
Yes, I can still reproduce this after disabling spellchecker. The output is no longer underscored, so I assume the write call that rewrote the line to underscore it is gone. I'm pretty sure the problem is between echo and clearHelpers respective outputs and spellchecker output happens well after it.

That said, I can't reproduce the effects of cursor going to the end of the line anymore, spellchecker on or off. That was quite late at night and I may have mistook the jump backward to jump to the end of the line. That or it has something to do with system load. It still goes backward and forward for no reason when pressing DEL, but it doesn't do big jumps.

I also found another thing while writing this. Going to the end of the string and holding DEL will make the cursor go backward one space and forward one space. That even reproduces without completion window open, but it is much harder to see. I think that confirms off-by-one somewhere.

**Comment by tsmish** [comment]
Here, I made a [video](https://github.com/lmorg/murex/assets/5459759/b8b0839a-e665-4412-ac4e-cd943b8e55e4).  At first I try backspacing with spellchecker on, then I hold DEL when the line says "ddbug". Then I do the same with spellchecker off.

**Comment by lmorg** [comment]
Curiously, this only seems to happen when autocompleting the command name. It doesn't for any parameters. Or at least I've not been able to recreate this for any command line parameters

**Comment by tsmish** [comment]
Removing `+ 1` from [this line](https://github.com/lmorg/murex/blob/09c2f4ad088208ccbc6f28f0450cbb73a0d427f0/utils/readline/write.go#L77) solves the problem, so I guess one of posX, lineX or `+ 1` is wrong. You mentioned vim mode, I guess this line is related to it, because from what I remember in normal mode cursor stays on character and in insert mode cursor goes one character forward. I don't really understand what that line means, but couldn't you make that `+ 1` conditional on having normal(?) mode enabled.

**Comment by lmorg** [comment]
Unfortunately that breaks other things too, like `ctrl+e`.

I think the cleanest approach here might just to be to buffer each write.

**Comment by tsmish** [comment]
I mean, buffering doesn't solve this off-by-one, it just makes it not noticeable. Buffering is just kind of annoying, you'll have to put a flush command in every place you finish rendering. But it makes things slightly more efficient and should be a complete solution to all the flickering problems.

**Comment by lmorg** [comment]
tbh the only reason this off by one error is a problem is due to the lack of buffering.
There is a couple of added benefits too:
- If I re-write each function that normally `print()`'s to return a `string` instead, that would make those functions easier to test 
- There is currently another rendering bug that's hard to solve because it's due to different processes running in parallel. I do have a mutex to limit when those processes can print, but reworking these functions would make it massively easier to handle those edge cases

To be honest, this is how the code should have been written from the outset. Live and learn.

**Comment by lmorg** [comment]
I've just pushed a readline rewrite to `develop`. I haven't yet done any extensive testing so there might be a few bugs in it still. I also need to rename a couple of methods. But on the whole, that commit should be pretty safe to run.

**Comment by lmorg** [comment]
Merged to `master`
