### ISSUE TITLE
Error on windows: Error creating table preview_command: Binary was compiled with 'CGO_ENABLED=0', go-sqlite3 requires cgo to work

### ISSUE THREAD

**Issue by nosly** [lmorg/murex#775]
Found a solution here, hope it helps:
[https://www.reddit.com/r/golang/comments/p7u6ui/golang_building_crossplatform_with_cgo_on_windows/](url)
If you are cross-compiling from Linux, here's the particular solution: 
[https://www.reddit.com/r/golang/comments/p7u6ui/comment/h9nl2q4/](url)

**Comment by lmorg** [comment]
@nosly 
Was this when compiling yourself or part of the pre-compiled Windows download?

Murex does already have a non-CGO version of sqlite3 also available under a different build flag: `-tags no_cgo`. eg
```
go build -tags no_cgo
```

The Windows downloads are built as static libraries so, in theory at least, it shouldn't matter that they were compiled with CGO because everything is bundled. However I don't have a Windows system to test this on.

If the Windows builds are failing to launch then I can always switch on the `no_cgo` flag for Winodws builds too (presently it's only enabled for Linux due to `libc` constraints and the (admittedly only slight) performance hit that the `no_cgo` sqlite3 library introduces.

**Comment by nosly** [comment]
It's part of the pre-compiled Windows download, and with this error, murex warns
!!! Disabling persistent cache !!!
on every launch, not sure whether it's serious problem or not, I just started to explore murex

**Comment by lmorg** [comment]
Cool. I'll get the build script updated to create a Windows binary without CGO.

As for the error itself, it's not an issue. All that means is that things like longer loading autocompletion scripts and such like wouldn't be cached between Murex sessions. Which was the norm last up until last month anyway. So it can be ignored.

> I just started to explore murex

I'd be interested to hear your thoughts

**Comment by lmorg** [comment]
Merged in `master`. New executables should automatically be built shortly: https://github.com/lmorg/murex/pull/776

**Comment by nosly** [comment]
> I'd be interested to hear your thoughts


Currently the configurations stay in a user's home like this, 
![image](https://github.com/lmorg/murex/assets/9146592/409ab4cb-c5ec-4843-8f08-90264aa10064)
I would prefer consolidate everything into one .murex dir under home, any way, just my personal preference. 

Compared to other similar shells, I find murex feature-rich and apis are stable for production use. 

The only major issue I see is the publicity of the project. It's like real gem buried in deep sea. Maybe in future can create youtube videos or cheat-sheet, participate in more discussions and etc. to improve the situation.

**Comment by nosly** [comment]
> Merged in `master`. New executables should automatically be built shortly: #776

Yes, problem solved, thanks for the quick fix!

**Comment by lmorg** [comment]
> > I'd be interested to hear your thoughts
> 
> Currently the configurations stay in a user's home like this, ![image](https://private-user-images.githubusercontent.com/9146592/291776613-409ab4cb-c5ec-4843-8f08-90264aa10064.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMwODY4NTgsIm5iZiI6MTcwMzA4NjU1OCwicGF0aCI6Ii85MTQ2NTkyLzI5MTc3NjYxMy00MDlhYjRjYi1jNWVjLTQ4NDMtOGYwOC05MDI2NGFhMTAwNjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQUlXTkpZQVg0Q1NWRUg1M0ElMkYyMDIzMTIyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyMzEyMjBUMTUzNTU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDRiNTBlZTA4NmI1NmYzMDBmOTlkMmE5NGUzMjU0YmU1YWVjYTE3YjFlNDY0ZjE5ZGQ2MDI1YTA1Y2ZkODllYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.eJH79zOjAmO4BVPqba076AUn2-9JLbzL8zv6fr57_d4) I would prefer consolidate everything into one .murex dir under home, any way, just my personal preference.

You can override the defaults via environmental variables[1] but you're right that it's a lot of stuff and not very well laid out. There was method to that madness originally (at first it was just `.murex_profile` and `.murex_history` so followed the same convention as bash, zsh, etc.

But since `.murex_modules` and `.murex_preload` has been introduced, there's a lot less sense following 40 year old conventions. So I've been giving serious thought to changing this default.

[1] https://murex.rocks/user-guide/profile.html

> Compared to other similar shells, I find murex feature-rich and apis are stable for production use.

Thank you :)

> 
> The only major issue I see is the publicity of the project. It's like real gem buried in deep sea. Maybe in future can create youtube videos or cheat-sheet, participate in more discussions and etc. to improve the situation.

I don't know if you've seen the language tour[2] and rosette stone[3]? The latter is effectively a cheat sheet. If they didn't meet your needs then I'd be interested to know what's missing that I need to document.

[2] https://murex.rocks/tour.html

[3] https://murex.rocks/user-guide/rosetta-stone.html

Regarding YouTube videos, I hadn't thought of that before. I do already have the equipment set up to do this because I stream retro games on Twitch most weeks (a little hobby with a group of friends). So YouTube videos is definitely something I could do. What kind of content were you thinking I should record?

**Comment by nosly** [comment]
> So I've been giving serious thought to changing this default.

Maybe it's good time to revamp the default.

> The latter is effectively a cheat sheet

You are absolutely right, thanks for the pointer. 

> What kind of content were you thinking I should record?

That depends on the target audience you want to attract. 
1. Introduction video(s)
	Audience:
	- newbies to shell scripting in general
	- newbies to murex only

	e.g. how to setup murex, simple snippets to showcase murex' capabilities & unique values
2. Intermediate to advanced topics
	Audience: 
	- existing bash users. Even if they may not be looking for a better alternative, by seeing true values from the video(s), they may give murex a try
	- users who see no place for shell scripting and resort anything to full-blown general purpose language. A video titled "Why murex is superior than python in these scenarios?" should at least catch their attention

	Topics should be from not too difficult to gradually complex ones, the aim is to show that it is easy and worthy to switch to murex

That's my 2 cents

**Comment by lmorg** [comment]
Thanks for the feedback. I’ll take that into consideration 👍
