### ISSUE TITLE
`expr` behaves inconsistently when invoked directly vs with `=` (deprecated)

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#827]
**Describe the bug:**
Invoking `expr` via `expr` gives different results than invoking it with `=` or just writing the expression.

**Expected behaviour:**
Invoking an expression by any of the 3 possible ways should provide the same result.

**Screenshots:**
![image](https://github.com/lmorg/murex/assets/138939221/66179e6d-b5e2-4493-9a5a-113ee7d805c3)

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: 6.9.7-arch1-1
 - Terminal Emulator: kitty 0.35.2
 - Murex version, output from `version --no-app-name`: 6.1.8300

**Additional context**
Bracketing the expression seems to fix the issue as a workaround. e.g. `expr (1 + 2)` gives 3.

**Comment by lmorg** [comment]
The `=` syntax is old code where I relied on a 3rd party module to handle expressions. However because the syntax for `=` and `expr` differs slightly (where I was able to make improvements to Murex's parser to natively support expressions), it meant I was nervous about replacing `=` with the new code as it would cause braking changes. But the `=` code is now deprecated and will be removed in the next major release of Murex.

`expr` wasn't intended to be invoked manually because there's some special-case code handling parsing of expressions to make them more ergonomic, and that always doesn't translate well to statements. This is something I should update the docs to reflect.

That all said, the issue you ran into was definitely a bug because `expr` was only checking the first parameter. That's now fixed in `develop`

**Comment by tiymat** [comment]
Thanks for the fix! The specific part of the documentation that led to me trying it was the last example of the `Usage` block here.
![image](https://github.com/lmorg/murex/assets/138939221/94cab5c5-99fc-4eb7-accc-b8db8a4ff23b)

**Comment by lmorg** [comment]
@tiymat that's a very good point. Is the new docs (only in `develop` at the moment) any clearer?
https://dev.murex.rocks/commands/expr.html#description

**Comment by tiymat** [comment]
> @tiymat that's a very good point. Is the new docs (only in `develop` at the moment) any clearer? https://dev.murex.rocks/commands/expr.html#description

Definitely!

**Comment by lmorg** [comment]
@tiymat looks like I've accidentally fixed `expr 1 + 2` when fixing something else unrelated 😅
