### ISSUE TITLE
Creating an empty array with fails: `%[]`

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#832]
**Describe the bug:**
From [the JSON spec](https://www.json.org/json-en.html) I believe creating an empty array is valid JSON (`'[' ws ']'` is one of the definitions of array there.)
`%[]` as an expression emits an error to stderr and returns a non-zero exitnum.
`x=%[]` does not emit an error and its exitnum is `0`, but the resulting variable's value is `null`.

**Expected behaviour:**
An array with no contents should be created.

**Screenshots:**
N/A

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: OS, output from uname -a if supported: 
 - Terminal Emulator: Terminal Emulator: kitty 0.35.2
 - Murex version, output from `version --no-app-name`: 6.1.8300

**Additional context**
Creating an empty map behaves as expected.

**Comment by lmorg** [comment]
Are you able to share your use case here?

I ask because arrays are a tricky one to get right in Murex because on the one hand, zero length arrays _should_ be a valid value. But on the other hand, they can cause execpected behaviour when paired with statement.

eg

```
cp $file @files $destination
```

if either `$file`, `$files` or `$destination` are unset, then you'll get an error. However if `@files` is a zero length array then `cp` might continue on (because `$file` already exists) and you'll get an uncaught error.

This example is rather convoluted but the point is arrays in Murex have been given special treatment where a zero length array is considered "incorrect" because it's an edge case for bugs.

Now I'm not suggested I can't make `%[]` support the creation of a zero length array, but because of the way the shell was designed, there would need to be a fair amount of testing in place to ensure that "_those_" instances support zero length and "_these_" do not (if you catch my drift?)

Understanding real world use cases will help me write those tests

**Comment by lmorg** [comment]
There's a few ways you can solve that.

For the sake demoing these possible methods, lets say you have a directory hierarchy that looks like:
```
.
├── a
│   ├── )rPsD8Dt5EtaC4*Yyn0q
│   ├── B[E3P2@gyzl2oSfvFs5(
│   ├── WNYBb>B{Y:9oBNq~eVn{
│   ├── W~e5bLBkGkv 2sr<XTj:
│   └── lgCVRC.PkUkh(!epI(ls
├── b
│   ├── ]^[;og5$x'%Zp* TY(NR
│   ├── kKcuV<9@pBrFr@"O\j?%
│   ├── wX'\>V`4P=K}FaxE^Hra
│   ├── yXjB#Cu'{%iLtsDCkKU%
│   └── |oK7e25Dz7z&ys.?2(]E
├── c
│   ├── )Kb!TOQ]\9J6 &<Y\2qj
│   ├── -X-Dm,m[JU0FZ#b0+fe+
│   ├── Lw2"`S<ag{EnJ=YI8A\W
│   ├── W4RUF_D.z,%M|OFsLB_A
│   └── z@meR3m7h(~V4m7(V{N
├── d
│   ├── %"6Tn]&w@Uas*Gi5$?Q0
│   ├── F}Ly:]zGTk}4]V+L=Wk+
│   ├── z%;lf^2n0r'p0Fy?f[$j
│   ├── {Iz}*#HCR_@H.KyA3=xy
│   └── ~2hUs'_NftfpH`?>Bqpt
├── e
│   ├── :#'G'Rs~^~A)g,k29Er1
│   ├── =N-KR9!lh"H FjCp@sP%
│   └── ?,E XTt%TGD4vrvR@qXw
└── f
    ├── !B#v!iYSBmi<i6[mdlL'
    ├── _@$*?WgS0KozEnmHV*gW
    ├── eT8?OgIK@4zSHTz0$m<O
    └── |c[c-8S.;X$&UzI@jp!X

7 directories, 27 files
```

And what you want to do is list just the files in directories that are vowels...

# merge operator

Annoyingly this isn't something I've documented, but there is a merge operator: `<~`

```
» %[a,e] -> foreach d { files <~ g($d/*) }
» $files
[
    "a/)rPsD8Dt5EtaC4*Yyn0q",
    "a/B[E3P2@gyzl2oSfvFs5(",
    "a/WNYBb\u003eB{Y:9oBNq~eVn{",
    "a/W~e5bLBkGkv 2sr\u003cXTj:",
    "a/lgCVRC.PkUkh(!epI(ls",
    "e/:#'G'Rs~^~A)g,k29Er1",
    "e/=N-KR9!lh\"H FjCp@sP%",
    "e/?,E XTt%TGD4vrvR@qXw"
]
```

The way this basically works is in an expression, it merges the right hand value into the left hand variable. Or if the variable doesn't exist, then it creates it.

If the target is an array, then it will append to the array.

# string lists

Since arrays don't have to be JSON, you can build a new line separated array too. For example:
```
» a a,e -> foreach d { g $d/* -> format str }
a/)rPsD8Dt5EtaC4*Yyn0q
a/B[E3P2@gyzl2oSfvFs5(
a/WNYBb>B{Y:9oBNq~eVn{
a/W~e5bLBkGkv 2sr<XTj:
a/lgCVRC.PkUkh(!epI(ls
e/:#'G'Rs~^~A)g,k29Er1
e/=N-KR9!lh"H FjCp@sP%
e/?,E XTt%TGD4vrvR@qXw
```
You can still convert that back to a JSON array with `-> format json` appended to the pipeline.

# trade offs

Method 1 is safer because you can have `\n` characters included in your values, which obviously new line delimited lists cannot. But its also slower because you're reading to and appending to a variable each time, and Murex just wasn't optimised for those types of operations. Depending on the size of your data, this might not be a problem.

Method 2 is quicker because the whole thing is just streaming to stdout. But it does come with a couple footguns:
1. your array elements cannot contain new lines (as discussed above)
2. `foreach` will make best guesses about what the output data type is. This is why I used `a a,e` instead of `%[a,e]`: the former creates an array as a `str` stream to stdout, the latter creates a `json` array. You can mitigate this problem with type casting though, eg `-> :str: format json`

---

Would any of the above solve your problem?

**Comment by lmorg** [comment]
Turns out fixing this bug was just required adding 3 characters 🤦 😆
