### ISSUE TITLE
Issue when using code block output as args

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#844]
**Describe the query:**
I'm not sure if this is a bug or a skill issue, but I'm having trouble using the output of one command as args/flags for another command.
![image](https://github.com/user-attachments/assets/ce7fe736-2395-420f-bdf3-f89818c33cd9)
This might seem like a contrived example but I ran into it after trying for ages to figure out why a command of the form `gcc ${ pkg-config --cflags some-lib } test.c ${ pkg-config --libs some-lib }` wasn't working, only to eventually try it in bash and see it succeed.

**Expected behaviour:**
That spaces in output from code block be able to delineate args.

**Additional context:**
N/A

**Documentation:**
Please rate your success with referring to the docs @ https://murex.rocks
- [ ] I haven't read the docs / the solution should be more discoverable
- [ ] I have read the docs but the content wasn't clear
- [x] I have read the docs but this query was missing
- [ ] I have read the docs and this query was answered but I'm still having problems

[add any additional detail, this will help us to write better docs]

**Comment by laurence-nearform** [comment]
Variables are properly tokenised in Murex so they don't need to be quoted. This solves problems like spaces in file names. So in your example `${ out "a z" }` is treated as a single string `"a z"`.

If you want to expand variables to cover multiple parameters then you need the `@` sigil instead. For example:

```
foobar = %[a, z]
cat @foobar
```

Similarly, sub-shells also support the different sigils:

```
cat @{ %[a, z] }
```

It's worth noting that `@{ out "a z" }` will still be interpreted as `"a z"` because you're outputting a string with a space in (ie the output of `out` is a single line string rather than an array).

**Comment by laurence-nearform** [comment]
This point is touched on in: https://murex.rocks/tour.html#sub-shells but I could do with making that clearer.

It looks like I copied the `$` doc but forgot to change it for `@` 🤦 https://murex.rocks/parser/array.html

I do also plan on writing some dedicated documentation for sub-shells too

**Comment by laurence-nearform** [comment]
@tiymat I think this is a failure of the docs not being clearer.
