### ISSUE TITLE
Can't redirect output to file that has been read from

### ISSUE THREAD

**Issue by tiymat** [lmorg/murex#851]
**Describe the bug:**
Reading from a file and redirecting output to that same file results in the file being truncated.

**Expected behaviour:**
The redirected output should appear in the file.

**Screenshots:**
Here, `cat a.txt |> a.txt` results in a.txt being truncated.
![image](https://github.com/user-attachments/assets/c355f6ec-964a-4b8c-a2c4-d1c20acb5f44)

**Platform (please complete the following information):**
 - OS, output from `uname -a` if supported: 6.10.2-arch1-1
 - Terminal Emulator: kitty 0.35.2
 - Murex version, output from `version --no-app-name`: 6.2.4000

**Additional context**
N/A

**Comment by lmorg** [comment]
This is a problem all shells have because you have yourself a race condition. Basically all POSIX shells runs commands in parallel by default. This is why they're performant at running pipelines on large files. So what's happening is the file is being truncated (`|>`) at the same time it is being read (`cat`).

If you want to read the file before writing to it, you either need to:
1. force the shell to run the commands sequentially rather than concurrently. eg `trypipe {cat a.txt |> a.txt}`, or
2. write to a temporary file, then delete the original, then rename that copy.
 
Personally I'd recommend method 2 because:
1. protects against any future optimisations in the shell that might reintroduce the aforementioned race condition
2. the On local file systems, it would actually be more performant to write to a temporary file for larger streams of data because you're running your pipeline in parallel (rather than waiting for one to finish before starting the next command), reducing the consumption of RAM (ie concurrent processes can stream bytes where as sequential execution requires the entire file to be loaded into cache before being passed to the STDIN of the next process), and on local file systems, delete and rename operations just alter file metadata rather than copying and zeroing the entire contents of a file.

---

It might be possible to provide a warning message about race conditions, if `>>` or `|>` are called and any other statement in the pipeline has a parameter that contains the same file name. But it wouldn't be terribly robust and I'm not sure you'd want to automatically fallback to sequential processing in scripts -- this should be something that's explicitly defined.

Maybe a new command or flag could work here, eg `|> --wait-for-eof a.txt` and that would tell `|>` not to open `a.txt` until it receives an EOF from stdin (ie the rest of the pipeline is complete). The problem with this is if you're parsing an 8GB file, then that's still 8GB of data that you're going to need to cache somewhere.

**Comment by lmorg** [comment]
I've been mulling this over a little more and just this month I ran into a situation where a wait flag would have been convenient. Yeah there's some risks if you're working with massive datasets, but that can be written about in the logs. However there is convenience in having it when writing a one liners from the interactive shell.

I can even add some rudimentary code that checks if any other process in a pipeline has that file open, and if so, produce a warning if that flag isn't present (if the shell is in interactive mode and the process isn't backgrounded)

**Comment by lmorg** [comment]
Early draft. Some tests are failing but that's good, it means the Murex tests are getting better at detecting edge cases. None-the-less, I think this early draft seems to work pretty well.

**Comment by lmorg** [comment]
@tiymat 

That right. But until the stdin operation on `|>` receives an EOF:

Does this doc make any sense?
https://github.com/lmorg/murex/blob/851/file-redirect/docs/parser/file-truncate.md
